//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.ClubSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClubSettingsLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClubSettingsLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.ClubSettings.ClubSettingsLocale", typeof(ClubSettingsLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New play mode.
        /// </summary>
        public static string AddPlayMode {
            get {
                return ResourceManager.GetString("AddPlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New season.
        /// </summary>
        public static string AddSeason {
            get {
                return ResourceManager.GetString("AddSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only members with one of these roles can use this play mode.
        /// </summary>
        public static string AllowedRolesHint {
            get {
                return ResourceManager.GetString("AllowedRolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age limit.
        /// </summary>
        public static string ChildAgeThreshold {
            get {
                return ResourceManager.GetString("ChildAgeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} closed.
        /// </summary>
        public static string ClosedCourtsChip {
            get {
                return ResourceManager.GetString("ClosedCourtsChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed from.
        /// </summary>
        public static string ClosedFrom {
            get {
                return ResourceManager.GetString("ClosedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed until.
        /// </summary>
        public static string ClosedTo {
            get {
                return ResourceManager.GetString("ClosedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed until {0}.
        /// </summary>
        public static string ClosedUntil {
            get {
                return ResourceManager.GetString("ClosedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end has to be after the start..
        /// </summary>
        public static string ClosureEndBeforeStart {
            get {
                return ResourceManager.GetString("ClosureEndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed from {0}.
        /// </summary>
        public static string ClosurePlanned {
            get {
                return ResourceManager.GetString("ClosurePlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string CourtAlias {
            get {
                return ResourceManager.GetString("CourtAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown in the booking grid on small screens.
        /// </summary>
        public static string CourtAliasHint {
            get {
                return ResourceManager.GetString("CourtAliasHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short name is required.
        /// </summary>
        public static string CourtAliasRequired {
            get {
                return ResourceManager.GetString("CourtAliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string CourtClosure {
            get {
                return ResourceManager.GetString("CourtClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During a closure the court cannot be booked, e.g. for maintenance.
        /// </summary>
        public static string CourtClosureHint {
            get {
                return ResourceManager.GetString("CourtClosureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CourtName {
            get {
                return ResourceManager.GetString("CourtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required.
        /// </summary>
        public static string CourtNameRequired {
            get {
                return ResourceManager.GetString("CourtNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CourtNaming {
            get {
                return ResourceManager.GetString("CourtNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CourtOpen {
            get {
                return ResourceManager.GetString("CourtOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} courts.
        /// </summary>
        public static string CourtsChip {
            get {
                return ResourceManager.GetString("CourtsChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is used on the booking page..
        /// </summary>
        public static string CourtsHint {
            get {
                return ResourceManager.GetString("CourtsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} courts – tap a court to rename or close it.
        /// </summary>
        public static string CourtsSubtitle {
            get {
                return ResourceManager.GetString("CourtsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courts.
        /// </summary>
        public static string CourtsTitle {
            get {
                return ResourceManager.GetString("CourtsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color.
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0} of {1}.
        /// </summary>
        public static string DayOf {
            get {
                return ResourceManager.GetString("DayOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days left.
        /// </summary>
        public static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the play mode "{0}"?.
        /// </summary>
        public static string DeletePlayModeConfirmation {
            get {
                return ResourceManager.GetString("DeletePlayModeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the season {0}? Enrollments and badges of this season are deleted as we[rest of string was truncated]&quot;.
        /// </summary>
        public static string DeleteSeasonConfirmation {
            get {
                return ResourceManager.GetString("DeleteSeasonConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any duration.
        /// </summary>
        public static string DurationFlexible {
            get {
                return ResourceManager.GetString("DurationFlexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court {0}.
        /// </summary>
        public static string EditCourtTitle {
            get {
                return ResourceManager.GetString("EditCourtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play mode {0}.
        /// </summary>
        public static string EditPlayModeTitle {
            get {
                return ResourceManager.GetString("EditPlayModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string EditSeasonTitle {
            get {
                return ResourceManager.GetString("EditSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club settings.
        /// </summary>
        public static string Eyebrow {
            get {
                return ResourceManager.GetString("Eyebrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts as match.
        /// </summary>
        public static string FlagCharging {
            get {
                return ResourceManager.GetString("FlagCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts for the booking limit, badges and the leaderboard.
        /// </summary>
        public static string FlagChargingHint {
            get {
                return ResourceManager.GetString("FlagChargingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string FlagComment {
            get {
                return ResourceManager.GetString("FlagComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members can add a comment.
        /// </summary>
        public static string FlagCommentHint {
            get {
                return ResourceManager.GetString("FlagCommentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overbooking.
        /// </summary>
        public static string FlagOverbook {
            get {
                return ResourceManager.GetString("FlagOverbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May overlap with other bookings.
        /// </summary>
        public static string FlagOverbookHint {
            get {
                return ResourceManager.GetString("FlagOverbookHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string FlagRecurring {
            get {
                return ResourceManager.GetString("FlagRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members can book weekly series.
        /// </summary>
        public static string FlagRecurringHint {
            get {
                return ResourceManager.GetString("FlagRecurringHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace period.
        /// </summary>
        public static string GracePeriod {
            get {
                return ResourceManager.GetString("GracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many minutes after the start a booking can still be made or cancelled.
        /// </summary>
        public static string GracePeriodHint {
            get {
                return ResourceManager.GetString("GracePeriodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed duration.
        /// </summary>
        public static string HasFixedDuration {
            get {
                return ResourceManager.GetString("HasFixedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed number of players.
        /// </summary>
        public static string HasFixedPlayerCount {
            get {
                return ResourceManager.GetString("HasFixedPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opening hours are invalid..
        /// </summary>
        public static string InvalidOpeningHours {
            get {
                return ResourceManager.GetString("InvalidOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prime time hours are invalid..
        /// </summary>
        public static string InvalidPrimeTimeHours {
            get {
                return ResourceManager.GetString("InvalidPrimeTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit per season.
        /// </summary>
        public static string LimitPerSeason {
            get {
                return ResourceManager.GetString("LimitPerSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active season.
        /// </summary>
        public static string NoActiveSeason {
            get {
                return ResourceManager.GetString("NoActiveSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members can only book during a season – add one below..
        /// </summary>
        public static string NoActiveSeasonHint {
            get {
                return ResourceManager.GetString("NoActiveSeasonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This club has no courts yet..
        /// </summary>
        public static string NoCourts {
            get {
                return ResourceManager.GetString("NoCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No play modes yet..
        /// </summary>
        public static string NoPlayModes {
            get {
                return ResourceManager.GetString("NoPlayModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seasons yet – add the first one..
        /// </summary>
        public static string NoSeasons {
            get {
                return ResourceManager.GetString("NoSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other duration.
        /// </summary>
        public static string OtherDuration {
            get {
                return ResourceManager.GetString("OtherDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlaps with season {0} ({1} – {2})..
        /// </summary>
        public static string OverlapWarning {
            get {
                return ResourceManager.GetString("OverlapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per season.
        /// </summary>
        public static string PerSeason {
            get {
                return ResourceManager.GetString("PerSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} players.
        /// </summary>
        public static string PlayersFixed {
            get {
                return ResourceManager.GetString("PlayersFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} player.
        /// </summary>
        public static string PlayersFixedOne {
            get {
                return ResourceManager.GetString("PlayersFixedOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any number of players.
        /// </summary>
        public static string PlayersFlexible {
            get {
                return ResourceManager.GetString("PlayersFlexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted.
        /// </summary>
        public static string PlayModeDeleted {
            get {
                return ResourceManager.GetString("PlayModeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New play mode.
        /// </summary>
        public static string PlayModeNamePlaceholder {
            get {
                return ResourceManager.GetString("PlayModeNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required.
        /// </summary>
        public static string PlayModeNameRequired {
            get {
                return ResourceManager.GetString("PlayModeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was saved.
        /// </summary>
        public static string PlayModeSaved {
            get {
                return ResourceManager.GetString("PlayModeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} play modes.
        /// </summary>
        public static string PlayModesChip {
            get {
                return ResourceManager.GetString("PlayModesChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What members can book and how.
        /// </summary>
        public static string PlayModesSubtitle {
            get {
                return ResourceManager.GetString("PlayModesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play modes.
        /// </summary>
        public static string PlayModesTitle {
            get {
                return ResourceManager.GetString("PlayModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime time.
        /// </summary>
        public static string PrimeTime {
            get {
                return ResourceManager.GetString("PrimeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime time {0} – {1}.
        /// </summary>
        public static string PrimeTimeChip {
            get {
                return ResourceManager.GetString("PrimeTimeChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most popular hours can be reserved for adult members.
        /// </summary>
        public static string PrimeTimeHint {
            get {
                return ResourceManager.GetString("PrimeTimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prime time has to be within the opening hours..
        /// </summary>
        public static string PrimeTimeOutsideOpeningHours {
            get {
                return ResourceManager.GetString("PrimeTimeOutsideOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        public static string PrimeTimeWeekdays {
            get {
                return ResourceManager.GetString("PrimeTimeWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max. {0} per season.
        /// </summary>
        public static string QuotaFact {
            get {
                return ResourceManager.GetString("QuotaFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No children in prime time.
        /// </summary>
        public static string RestrictChildren {
            get {
                return ResourceManager.GetString("RestrictChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members younger than {0} cannot book prime time.
        /// </summary>
        public static string RestrictChildrenHint {
            get {
                return ResourceManager.GetString("RestrictChildrenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guests in prime time.
        /// </summary>
        public static string RestrictGuests {
            get {
                return ResourceManager.GetString("RestrictGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest cards cannot be used during prime time.
        /// </summary>
        public static string RestrictGuestsHint {
            get {
                return ResourceManager.GetString("RestrictGuestsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one role..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours and rules saved.
        /// </summary>
        public static string RulesSaved {
            get {
                return ResourceManager.GetString("RulesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When courts can be booked and who may play in prime time.
        /// </summary>
        public static string RulesSubtitle {
            get {
                return ResourceManager.GetString("RulesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours &amp; rules.
        /// </summary>
        public static string RulesTitle {
            get {
                return ResourceManager.GetString("RulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days break.
        /// </summary>
        public static string SeasonBreak {
            get {
                return ResourceManager.GetString("SeasonBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After creating a season, enroll the members on the members page..
        /// </summary>
        public static string SeasonHint {
            get {
                return ResourceManager.GetString("SeasonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks · {1} days.
        /// </summary>
        public static string SeasonLength {
            get {
                return ResourceManager.GetString("SeasonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string SeasonName {
            get {
                return ResourceManager.GetString("SeasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string SeasonPeriod {
            get {
                return ResourceManager.GetString("SeasonPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlaps by {0} days.
        /// </summary>
        public static string SeasonsOverlap {
            get {
                return ResourceManager.GetString("SeasonsOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members book within a season they are enrolled in.
        /// </summary>
        public static string SeasonsSubtitle {
            get {
                return ResourceManager.GetString("SeasonsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string SeasonState_active {
            get {
                return ResourceManager.GetString("SeasonState_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string SeasonState_past {
            get {
                return ResourceManager.GetString("SeasonState_past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string SeasonState_upcoming {
            get {
                return ResourceManager.GetString("SeasonState_upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string SeasonsTitle {
            get {
                return ResourceManager.GetString("SeasonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who may book.
        /// </summary>
        public static string SectionAccess {
            get {
                return ResourceManager.GetString("SectionAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; color.
        /// </summary>
        public static string SectionBasics {
            get {
                return ResourceManager.GetString("SectionBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string SectionRules {
            get {
                return ResourceManager.GetString("SectionRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts in {0} days.
        /// </summary>
        public static string StartsIn {
            get {
                return ResourceManager.GetString("StartsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours, seasons, courts and play modes of your club.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} like last season.
        /// </summary>
        public static string SuggestNextSeason {
            get {
                return ResourceManager.GetString("SuggestNextSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours and prime time of a day.
        /// </summary>
        public static string TimelineDescription {
            get {
                return ResourceManager.GetString("TimelineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
