<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Fusonic.Extensions.Common" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\global\Bookennis.Global.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Leaderboards\" />
  </ItemGroup>

</Project>
