//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.BadgeSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BadgeSettingsLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BadgeSettingsLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.BadgeSettings.BadgeSettingsLocale", typeof(BadgeSettingsLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New special award.
        /// </summary>
        public static string AddOneTimeBadge {
            get {
                return ResourceManager.GetString("AddOneTimeBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New level.
        /// </summary>
        public static string AddTier {
            get {
                return ResourceManager.GetString("AddTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded {0}×.
        /// </summary>
        public static string AwardedTo {
            get {
                return ResourceManager.GetString("AwardedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} times earned.
        /// </summary>
        public static string AwardsChip {
            get {
                return ResourceManager.GetString("AwardsChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award {0}.
        /// </summary>
        public static string AwardTitle {
            get {
                return ResourceManager.GetString("AwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from another season.
        /// </summary>
        public static string CopyOneTime {
            get {
                return ResourceManager.GetString("CopyOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from another season.
        /// </summary>
        public static string CopyTiers {
            get {
                return ResourceManager.GetString("CopyTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the special award "{0}"?.
        /// </summary>
        public static string DeleteOneTimeConfirmation {
            get {
                return ResourceManager.GetString("DeleteOneTimeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the level "{0}"?.
        /// </summary>
        public static string DeleteTierConfirmation {
            get {
                return ResourceManager.GetString("DeleteTierConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown to members in their trophy case.
        /// </summary>
        public static string DescriptionHint {
            get {
                return ResourceManager.GetString("DescriptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earned.
        /// </summary>
        public static string Earned {
            get {
                return ResourceManager.GetString("Earned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned by {0} members.
        /// </summary>
        public static string EarnedBy {
            get {
                return ResourceManager.GetString("EarnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must not be larger than 5 MB..
        /// </summary>
        public static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded.
        /// </summary>
        public static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        public static string LevelPill {
            get {
                return ResourceManager.GetString("LevelPill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches.
        /// </summary>
        public static string MatchesRule {
            get {
                return ResourceManager.GetString("MatchesRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No special awards in this season.
        /// </summary>
        public static string NoOneTime {
            get {
                return ResourceManager.GetString("NoOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honor club champions, the most improved player or your helpers of the year..
        /// </summary>
        public static string NoOneTimeText {
            get {
                return ResourceManager.GetString("NoOneTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a season first, badges belong to a season..
        /// </summary>
        public static string NoSeasons {
            get {
                return ResourceManager.GetString("NoSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not awarded yet.
        /// </summary>
        public static string NotAwardedYet {
            get {
                return ResourceManager.GetString("NotAwardedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No badge earned yet.
        /// </summary>
        public static string NothingEarnedYet {
            get {
                return ResourceManager.GetString("NothingEarnedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No levels in this season.
        /// </summary>
        public static string NoTiers {
            get {
                return ResourceManager.GetString("NoTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create levels like bronze, silver and gold – members earn them with every played match..
        /// </summary>
        public static string NoTiersText {
            get {
                return ResourceManager.GetString("NoTiersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} special awards.
        /// </summary>
        public static string OneTimeChip {
            get {
                return ResourceManager.GetString("OneTimeChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New special award.
        /// </summary>
        public static string OneTimeNamePlaceholder {
            get {
                return ResourceManager.GetString("OneTimeNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded by hand.
        /// </summary>
        public static string OneTimeRule {
            get {
                return ResourceManager.GetString("OneTimeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded by hand, e.g. to the club champion.
        /// </summary>
        public static string OneTimeSubtitle {
            get {
                return ResourceManager.GetString("OneTimeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special awards.
        /// </summary>
        public static string OneTimeTitle {
            get {
                return ResourceManager.GetString("OneTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous level {0}: {1} matches.
        /// </summary>
        public static string PreviousTierHint {
            get {
                return ResourceManager.GetString("PreviousTierHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string SeasonCaption {
            get {
                return ResourceManager.GetString("SeasonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string SeasonName {
            get {
                return ResourceManager.GetString("SeasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special award.
        /// </summary>
        public static string SpecialAward {
            get {
                return ResourceManager.GetString("SpecialAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward your members for playing – with levels and special awards.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher levels should need more matches than the previous one..
        /// </summary>
        public static string ThresholdNotIncreasing {
            get {
                return ResourceManager.GetString("ThresholdNotIncreasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New level.
        /// </summary>
        public static string TierNamePlaceholder {
            get {
                return ResourceManager.GetString("TierNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} levels.
        /// </summary>
        public static string TiersChip {
            get {
                return ResourceManager.GetString("TiersChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned automatically by playing matches – tap a badge to preview it.
        /// </summary>
        public static string TiersSubtitle {
            get {
                return ResourceManager.GetString("TiersSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string TiersTitle {
            get {
                return ResourceManager.GetString("TiersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest level reached: {0} ({1}×).
        /// </summary>
        public static string TopEarned {
            get {
                return ResourceManager.GetString("TopEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
    }
}
