// <auto-generated />
using System;
using Bookennis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookennis.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240320203935_UpdateUserRoleNames")]
    partial class UpdateUserRoleNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("BookingEntryPlayers_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Bookings_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Clubs_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Courts_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Families_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("FamilyMembers_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Members_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Users_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tennis.Domain.Booking.BookingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Bookings_Id_Sequence");

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tennis.Domain.Booking.BookingEntryPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "BookingEntryPlayers_Id_Sequence");

                    b.Property<int>("BookingEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("BookingEntryId", "MemberId");

                    b.ToTable("BookingEntryPlayers");
                });

            modelBuilder.Entity("Tennis.Domain.Booking.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Clubs_Id_Sequence");

                    b.Property<int>("DefaultBookingsPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultBookingsPerWeek = 10,
                            Name = "TC Vorderland"
                        });
                });

            modelBuilder.Entity("Tennis.Domain.Booking.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Courts_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InactiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InactiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            Name = "1"
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 1,
                            Name = "2"
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 1,
                            Name = "3"
                        },
                        new
                        {
                            Id = 4,
                            ClubId = 1,
                            Name = "4"
                        },
                        new
                        {
                            Id = 5,
                            ClubId = 1,
                            Name = "5"
                        },
                        new
                        {
                            Id = 6,
                            ClubId = 1,
                            Name = "6"
                        },
                        new
                        {
                            Id = 7,
                            ClubId = 1,
                            Name = "7"
                        });
                });

            modelBuilder.Entity("Tennis.Domain.Families.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Families_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Tennis.Domain.Families.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "FamilyMembers_Id_Sequence");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("UX_FamilyMembers_MemberId");

                    b.ToTable("FamilyMembers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FamilyMember");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tennis.Domain.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Members_Id_Sequence");

                    b.Property<int?>("BookingsPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAllowedToBook")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Tennis.Domain.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Users_Id_Sequence");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BelongsToUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tennis.Domain.User.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Tennis.Domain.Families.ChildFamilyMember", b =>
                {
                    b.HasBaseType("Tennis.Domain.Families.FamilyMember");

                    b.Property<int>("ChildFamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("ChildFamilyId");

                    b.HasDiscriminator().HasValue("ChildFamilyMember");
                });

            modelBuilder.Entity("Tennis.Domain.Families.ParentFamilyMember", b =>
                {
                    b.HasBaseType("Tennis.Domain.Families.FamilyMember");

                    b.Property<int>("ParentFamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("ParentFamilyId");

                    b.HasDiscriminator().HasValue("ParentFamilyMember");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Tennis.Domain.User.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Tennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Tennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Tennis.Domain.User.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Tennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Booking.BookingEntry", b =>
                {
                    b.HasOne("Tennis.Domain.Booking.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Court");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Booking.BookingEntryPlayer", b =>
                {
                    b.HasOne("Tennis.Domain.Booking.BookingEntry", "BookingEntry")
                        .WithMany("Players")
                        .HasForeignKey("BookingEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tennis.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("BookingEntryPlayers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("BookingEntry");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Booking.Club", b =>
                {
                    b.OwnsOne("Tennis.Domain.Booking.OpeningHours", "OpeningHours", b1 =>
                        {
                            b1.Property<int>("ClubId")
                                .HasColumnType("integer");

                            b1.Property<int>("From")
                                .HasColumnType("integer");

                            b1.Property<int>("To")
                                .HasColumnType("integer");

                            b1.HasKey("ClubId");

                            b1.ToTable("Clubs");

                            b1.WithOwner()
                                .HasForeignKey("ClubId");
                        });

                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Clubs");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("OpeningHours")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Booking.Court", b =>
                {
                    b.HasOne("Tennis.Domain.Booking.Club", "Club")
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Courts");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Club");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Families.Family", b =>
                {
                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Families");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Families.FamilyMember", b =>
                {
                    b.HasOne("Tennis.Domain.Families.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("FamilyMembers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Family");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Members.Member", b =>
                {
                    b.HasOne("Tennis.Domain.Booking.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.User.User", b =>
                {
                    b.OwnsOne("Tennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Tennis.Domain.Families.ChildFamilyMember", b =>
                {
                    b.HasOne("Tennis.Domain.Families.Family", "ChildFamily")
                        .WithMany("Children")
                        .HasForeignKey("ChildFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildFamily");
                });

            modelBuilder.Entity("Tennis.Domain.Families.ParentFamilyMember", b =>
                {
                    b.HasOne("Tennis.Domain.Families.Family", "ParentFamily")
                        .WithMany("Parents")
                        .HasForeignKey("ParentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFamily");
                });

            modelBuilder.Entity("Tennis.Domain.Booking.BookingEntry", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Tennis.Domain.Booking.Club", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("Tennis.Domain.Booking.Court", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Tennis.Domain.Families.Family", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FamilyMembers");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
