// <auto-generated />
using System;
using Bookennis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookennis.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515122838_AddReoccurringBookings")]
    partial class AddReoccurringBookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("BookingPlayers_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Bookings_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Clubs_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Courts_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Families_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("FamilyMembers_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("GuestCards_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Members_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("MemberSeasons_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("PlayModes_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("RecurringBookingSeries_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("RecurringBookingSeriesPlayers_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Seasons_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.HasSequence<int>("Users_Id_Sequence")
                .StartsAt(10L)
                .IncrementsBy(10);

            modelBuilder.Entity("Bookennis.Domain.Bookings.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Bookings_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExcludedFromSeries")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayModeId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurringBookingSeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneInfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CourtId");

                    b.HasIndex("PlayModeId");

                    b.HasIndex("RecurringBookingSeriesId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.BookingPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "BookingPlayers_Id_Sequence");

                    b.Property<int>("BookingEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("BookingEntryId", "MemberId");

                    b.ToTable("BookingPlayers");
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.RecurringBookingSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "RecurringBookingSeries_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PlayModeId")
                        .HasColumnType("integer");

                    b.Property<int>("RecurrenceIntervalWeeks")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimeZoneInfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CourtId");

                    b.HasIndex("PlayModeId");

                    b.ToTable("RecurringBookingSeries");
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.RecurringBookingSeriesPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "RecurringBookingSeriesPlayers_Id_Sequence");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("RecurringBookingSeriesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RecurringBookingSeriesId", "MemberId");

                    b.ToTable("RecurringBookingSeriesPlayers");
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Clubs_Id_Sequence");

                    b.Property<int?>("BookingGracePeriodInMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ConcurrentAllowedBookings")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtpClub")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.PlayMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "PlayModes_Id_Sequence");

                    b.Property<bool>("AllowRecurring")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("CanOverbook")
                        .HasColumnType("boolean");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<bool>("CommentAllowed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("FixedDuration")
                        .HasColumnType("interval");

                    b.Property<int?>("FixedPlayerCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChargingBookingSubscription")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxBookingsPerSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("PlayModes");
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Seasons_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Bookennis.Domain.Courts.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Courts_Id_Sequence");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Bookennis.Domain.Families.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Families_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Bookennis.Domain.Families.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "FamilyMembers_Id_Sequence");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("UX_FamilyMembers_MemberId");

                    b.ToTable("FamilyMembers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FamilyMember");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bookennis.Domain.Guests.GuestCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "GuestCards_Id_Sequence");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid");

                    b.Property<int>("GuestMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchasedBookings")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("GuestMemberId");

                    b.ToTable("GuestCards");
                });

            modelBuilder.Entity("Bookennis.Domain.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Members_Id_Sequence");

                    b.Property<int?>("BookingsPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAllowedToBook")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("UserRoles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Members", (string)null);

                    b.HasDiscriminator<int>("MemberType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bookennis.Domain.Members.MemberSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MemberSeasons_Id_Sequence");

                    b.Property<bool>("LeaderboardOptOut")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("MemberId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("UX_MemberSeasons_MemberId_SeasonId");

                    b.ToTable("MemberSeasons");
                });

            modelBuilder.Entity("Bookennis.Domain.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Users_Id_Sequence");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BelongsToUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int>("Country")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Bookennis.Domain.User.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bookennis.Domain.Families.ChildFamilyMember", b =>
                {
                    b.HasBaseType("Bookennis.Domain.Families.FamilyMember");

                    b.Property<int>("ChildFamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("ChildFamilyId");

                    b.HasDiscriminator().HasValue("ChildFamilyMember");
                });

            modelBuilder.Entity("Bookennis.Domain.Families.ParentFamilyMember", b =>
                {
                    b.HasBaseType("Bookennis.Domain.Families.FamilyMember");

                    b.Property<int>("ParentFamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("ParentFamilyId");

                    b.HasDiscriminator().HasValue("ParentFamilyMember");
                });

            modelBuilder.Entity("Bookennis.Domain.Members.ClubMember", b =>
                {
                    b.HasBaseType("Bookennis.Domain.Members.Member");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Bookennis.Domain.Members.GuestMember", b =>
                {
                    b.HasBaseType("Bookennis.Domain.Members.Member");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Courts.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Clubs.PlayMode", null)
                        .WithMany()
                        .HasForeignKey("PlayModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Bookings.RecurringBookingSeries", "RecurringBookingSeries")
                        .WithMany()
                        .HasForeignKey("RecurringBookingSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Bookennis.Global.Intervals.DateTimeOffsetInterval", "Interval", b1 =>
                        {
                            b1.Property<int>("BookingId")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("BookingId");

                            b1.HasIndex("From");

                            b1.HasIndex("To");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Interval")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("RecurringBookingSeries");
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.BookingPlayer", b =>
                {
                    b.HasOne("Bookennis.Domain.Bookings.Booking", "Booking")
                        .WithMany("Players")
                        .HasForeignKey("BookingEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Members.ClubMember", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("BookingPlayers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Booking");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.RecurringBookingSeries", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Courts.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Clubs.PlayMode", null)
                        .WithMany()
                        .HasForeignKey("PlayModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("RecurringBookingSeries");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.RecurringBookingSeriesPlayer", b =>
                {
                    b.HasOne("Bookennis.Domain.Members.ClubMember", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Bookings.RecurringBookingSeries", "Series")
                        .WithMany("SeriesPlayers")
                        .HasForeignKey("RecurringBookingSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("RecurringBookingSeriesPlayers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.Club", b =>
                {
                    b.OwnsOne("Bookennis.Global.Intervals.TimeOnlyInterval", "OpeningHours", b1 =>
                        {
                            b1.Property<int>("ClubId")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("From")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("To")
                                .HasColumnType("time without time zone");

                            b1.HasKey("ClubId");

                            b1.HasIndex("From");

                            b1.HasIndex("To");

                            b1.ToTable("Clubs");

                            b1.WithOwner()
                                .HasForeignKey("ClubId");
                        });

                    b.OwnsOne("Bookennis.Domain.Clubs.PrimeTimeSettings", "PrimeTimeSettings", b1 =>
                        {
                            b1.Property<int>("ClubId")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<int[]>("ApplicableWeekdays")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int>("ChildAgeThreshold")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean");

                            b1.Property<bool>("RestrictChildren")
                                .HasColumnType("boolean");

                            b1.Property<bool>("RestrictGuests")
                                .HasColumnType("boolean");

                            b1.HasKey("ClubId");

                            b1.ToTable("Clubs");

                            b1.WithOwner()
                                .HasForeignKey("ClubId");

                            b1.OwnsOne("Bookennis.Global.Intervals.TimeOnlyInterval", "PrimeTimeHours", b2 =>
                                {
                                    b2.Property<int>("PrimeTimeSettingsClubId")
                                        .HasColumnType("integer");

                                    b2.Property<TimeOnly>("From")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly>("To")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("PrimeTimeSettingsClubId");

                                    b2.HasIndex("From")
                                        .IsDescending();

                                    b2.HasIndex("To")
                                        .IsDescending();

                                    b2.ToTable("Clubs");

                                    b2.WithOwner()
                                        .HasForeignKey("PrimeTimeSettingsClubId");
                                });

                            b1.Navigation("PrimeTimeHours")
                                .IsRequired();
                        });

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Clubs");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("OpeningHours")
                        .IsRequired();

                    b.Navigation("PrimeTimeSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.PlayMode", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", "Club")
                        .WithMany("PlayModes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("PlayModes");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Club");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.Season", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", null)
                        .WithMany("Seasons")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Seasons");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.OwnsOne("Bookennis.Global.Intervals.DateOnlyInterval", "Period", b1 =>
                        {
                            b1.Property<int>("SeasonId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date");

                            b1.HasKey("SeasonId");

                            b1.HasIndex("From")
                                .IsDescending();

                            b1.HasIndex("To")
                                .IsDescending();

                            b1.ToTable("Seasons");

                            b1.WithOwner()
                                .HasForeignKey("SeasonId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Courts.Court", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Global.Intervals.DateTimeOffsetInterval", "Inactive", b1 =>
                        {
                            b1.Property<int>("CourtId")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CourtId");

                            b1.HasIndex("From")
                                .IsDescending();

                            b1.HasIndex("To")
                                .IsDescending();

                            b1.ToTable("Courts");

                            b1.WithOwner()
                                .HasForeignKey("CourtId");
                        });

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Courts");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Inactive");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Families.Family", b =>
                {
                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Families");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Families.FamilyMember", b =>
                {
                    b.HasOne("Bookennis.Domain.Families.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("FamilyMembers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Family");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Guests.GuestCard", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Members.GuestMember", null)
                        .WithMany()
                        .HasForeignKey("GuestMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("GuestCards");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Members.Member", b =>
                {
                    b.HasOne("Bookennis.Domain.Clubs.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Members.MemberSeason", b =>
                {
                    b.HasOne("Bookennis.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.Clubs.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("MemberSeasons");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.User.User", b =>
                {
                    b.OwnsOne("Bookennis.Domain.Base.EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<int?>("CreationUserId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModificationUserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Modified")
                                .IsConcurrencyToken()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Bookennis.Domain.User.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Bookennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Bookennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Bookennis.Domain.User.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Bookennis.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookennis.Domain.Families.ChildFamilyMember", b =>
                {
                    b.HasOne("Bookennis.Domain.Families.Family", "ChildFamily")
                        .WithMany("Children")
                        .HasForeignKey("ChildFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildFamily");
                });

            modelBuilder.Entity("Bookennis.Domain.Families.ParentFamilyMember", b =>
                {
                    b.HasOne("Bookennis.Domain.Families.Family", "ParentFamily")
                        .WithMany("Parents")
                        .HasForeignKey("ParentFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFamily");
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Bookennis.Domain.Bookings.RecurringBookingSeries", b =>
                {
                    b.Navigation("SeriesPlayers");
                });

            modelBuilder.Entity("Bookennis.Domain.Clubs.Club", b =>
                {
                    b.Navigation("PlayModes");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Bookennis.Domain.Families.Family", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FamilyMembers");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
