//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.SubscriptionPlanner {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubscriptionPlannerLocale {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriptionPlannerLocale() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.SubscriptionPlanner.SubscriptionPlannerLocale", typeof(SubscriptionPlannerLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} weeks will be scheduled..
        /// </summary>
        public static string ActiveWeeksSummary {
            get {
                return ResourceManager.GetString("ActiveWeeksSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap the weeks in which a participant can't play. Crossed out weeks are not available..
        /// </summary>
        public static string AvailabilityHelp {
            get {
                return ResourceManager.GetString("AvailabilityHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to all plans.
        /// </summary>
        public static string BackToPlans {
            get {
                return ResourceManager.GetString("BackToPlans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap the weeks in which nobody should be scheduled (e.g. holidays). Crossed out weeks are skipped..
        /// </summary>
        public static string BlockedWeeksHelp {
            get {
                return ResourceManager.GetString("BlockedWeeksHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CW.
        /// </summary>
        public static string CalendarWeekShort {
            get {
                return ResourceManager.GetString("CalendarWeekShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change color.
        /// </summary>
        public static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compute schedule.
        /// </summary>
        public static string Compute {
            get {
                return ResourceManager.GetString("Compute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Everything is ready. Compute the schedule now..
        /// </summary>
        public static string ComputeHelp {
            get {
                return ResourceManager.GetString("ComputeHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete plan.
        /// </summary>
        public static string DeletePlan {
            get {
                return ResourceManager.GetString("DeletePlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the plan "{0}"?.
        /// </summary>
        public static string DeletePlanConfirm {
            get {
                return ResourceManager.GetString("DeletePlanConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download Excel.
        /// </summary>
        public static string DownloadExcel {
            get {
                return ResourceManager.GetString("DownloadExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This name is already in the list..
        /// </summary>
        public static string DuplicateParticipant {
            get {
                return ResourceManager.GetString("DuplicateParticipant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a name and a valid period first..
        /// </summary>
        public static string FixBasicsFirst {
            get {
                return ResourceManager.GetString("FixBasicsFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Games per participant.
        /// </summary>
        public static string GamesPerParticipant {
            get {
                return ResourceManager.GetString("GamesPerParticipant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show as table.
        /// </summary>
        public static string GridView {
            get {
                return ResourceManager.GetString("GridView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name of the participant.
        /// </summary>
        public static string NewParticipant {
            get {
                return ResourceManager.GetString("NewParticipant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New plan.
        /// </summary>
        public static string NewPlan {
            get {
                return ResourceManager.GetString("NewPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nobody else is available in this week..
        /// </summary>
        public static string NoAvailablePlayers {
            get {
                return ResourceManager.GetString("NoAvailablePlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No participants yet..
        /// </summary>
        public static string NoParticipantsYet {
            get {
                return ResourceManager.GetString("NoParticipantsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have no plans yet. Create your first plan to get started..
        /// </summary>
        public static string NoPlansYet {
            get {
                return ResourceManager.GetString("NoPlansYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No play.
        /// </summary>
        public static string NoPlay {
            get {
                return ResourceManager.GetString("NoPlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least {0} participants are needed to create a schedule..
        /// </summary>
        public static string NotEnoughParticipants {
            get {
                return ResourceManager.GetString("NotEnoughParticipants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenPlan {
            get {
                return ResourceManager.GetString("OpenPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Who plays with whom?.
        /// </summary>
        public static string PairMatrix {
            get {
                return ResourceManager.GetString("PairMatrix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number of weeks two participants play together. Green means close to the fair value, red means far o....
        /// </summary>
        public static string PairMatrixHelp {
            get {
                return ResourceManager.GetString("PairMatrixHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} weeks together (fair: {1}).
        /// </summary>
        public static string PairTooltip {
            get {
                return ResourceManager.GetString("PairTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} participants.
        /// </summary>
        public static string ParticipantsCount {
            get {
                return ResourceManager.GetString("ParticipantsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter everyone who shares the subscription. They don't have to be club members. The share defines ho....
        /// </summary>
        public static string ParticipantsHelp {
            get {
                return ResourceManager.GetString("ParticipantsHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} per week.
        /// </summary>
        public static string PerWeekCount {
            get {
                return ResourceManager.GetString("PerWeekCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plan name.
        /// </summary>
        public static string PlanName {
            get {
                return ResourceManager.GetString("PlanName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The plan could not be found..
        /// </summary>
        public static string PlanNotFound {
            get {
                return ResourceManager.GetString("PlanNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plan your group's winter subscription: add the players, cross out the weeks nobody plays and let the....
        /// </summary>
        public static string PlannerIntro {
            get {
                return ResourceManager.GetString("PlannerIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Players per week.
        /// </summary>
        public static string PlayersPerWeek {
            get {
                return ResourceManager.GetString("PlayersPerWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 2 for singles, 4 for doubles.
        /// </summary>
        public static string PlayersPerWeekHelp {
            get {
                return ResourceManager.GetString("PlayersPerWeekHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemovePlayer {
            get {
                return ResourceManager.GetString("RemovePlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplacePlayer {
            get {
                return ResourceManager.GetString("ReplacePlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule ready.
        /// </summary>
        public static string ScheduleReady {
            get {
                return ResourceManager.GetString("ScheduleReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule will be reset.
        /// </summary>
        public static string ScheduleWillBeCleared {
            get {
                return ResourceManager.GetString("ScheduleWillBeCleared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your changes affect the schedule. If you save them, the current schedule (including manual changes) ....
        /// </summary>
        public static string ScheduleWillBeClearedText {
            get {
                return ResourceManager.GetString("ScheduleWillBeClearedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share (%).
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compute again.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A new schedule replaces the current one including your manual changes. Continue?.
        /// </summary>
        public static string ShuffleConfirm {
            get {
                return ResourceManager.GetString("ShuffleConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The start date must not be after the end date..
        /// </summary>
        public static string StartAfterEnd {
            get {
                return ResourceManager.GetString("StartAfterEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string StepAvailability {
            get {
                return ResourceManager.GetString("StepAvailability", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string StepBasics {
            get {
                return ResourceManager.GetString("StepBasics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weeks off.
        /// </summary>
        public static string StepBlockedWeeks {
            get {
                return ResourceManager.GetString("StepBlockedWeeks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string StepParticipants {
            get {
                return ResourceManager.GetString("StepParticipants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string StepSchedule {
            get {
                return ResourceManager.GetString("StepSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription planner.
        /// </summary>
        public static string SubscriptionPlanner {
            get {
                return ResourceManager.GetString("SubscriptionPlanner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap a player to swap them with someone else..
        /// </summary>
        public static string SwapHelp {
            get {
                return ResourceManager.GetString("SwapHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To the schedule.
        /// </summary>
        public static string ToSchedule {
            get {
                return ResourceManager.GetString("ToSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} weeks unavailable.
        /// </summary>
        public static string UnavailableWeeksCount {
            get {
                return ResourceManager.GetString("UnavailableWeeksCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not enough players are available in this week..
        /// </summary>
        public static string Understaffed {
            get {
                return ResourceManager.GetString("Understaffed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The period covers {0} calendar weeks..
        /// </summary>
        public static string WeeksInRange {
            get {
                return ResourceManager.GetString("WeeksInRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
    }
}
