//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.Statistics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatisticsLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticsLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.Statistics.StatisticsLocale", typeof(StatisticsLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ActivityCalendar {
            get {
                return ResourceManager.GetString("ActivityCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every square is a day of the season.
        /// </summary>
        public static string ActivityCalendarSubtitle {
            get {
                return ResourceManager.GetString("ActivityCalendarSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        public static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tennis career.
        /// </summary>
        public static string AllTimeHeroTitle {
            get {
                return ResourceManager.GetString("AllTimeHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. partner age.
        /// </summary>
        public static string AverageOpponentAge {
            get {
                return ResourceManager.GetString("AverageOpponentAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best week.
        /// </summary>
        public static string BestWeek {
            get {
                return ResourceManager.GetString("BestWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You played more matches than {0} of the other {1} members..
        /// </summary>
        public static string BetterThanSentence {
            get {
                return ResourceManager.GetString("BetterThanSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between two matches.
        /// </summary>
        public static string BetweenTwoMatches {
            get {
                return ResourceManager.GetString("BetweenTwoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busiest month.
        /// </summary>
        public static string BusiestMonth {
            get {
                return ResourceManager.GetString("BusiestMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By time of day.
        /// </summary>
        public static string ByTimeOfDay {
            get {
                return ResourceManager.GetString("ByTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By weekday.
        /// </summary>
        public static string ByWeekday {
            get {
                return ResourceManager.GetString("ByWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club average.
        /// </summary>
        public static string ClubAverage {
            get {
                return ResourceManager.GetString("ClubAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your courts.
        /// </summary>
        public static string CourtUsage {
            get {
                return ResourceManager.GetString("CourtUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks in a row.
        /// </summary>
        public static string CurrentStreakChip {
            get {
                return ResourceManager.GetString("CurrentStreakChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string DaysCount {
            get {
                return ResourceManager.GetString("DaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different partners.
        /// </summary>
        public static string DifferentPartners {
            get {
                return ResourceManager.GetString("DifferentPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your dream team.
        /// </summary>
        public static string DreamTeam {
            get {
                return ResourceManager.GetString("DreamTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} different partners.
        /// </summary>
        public static string DreamTeamSubtitle {
            get {
                return ResourceManager.GetString("DreamTeamSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite court.
        /// </summary>
        public static string FavouriteCourt {
            get {
                return ResourceManager.GetString("FavouriteCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your favourite day is {0}, preferably at {1}..
        /// </summary>
        public static string FavouriteDaySentence {
            get {
                return ResourceManager.GetString("FavouriteDaySentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First match.
        /// </summary>
        public static string FirstMatch {
            get {
                return ResourceManager.GetString("FirstMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours on court.
        /// </summary>
        public static string HoursOnCourtSentence {
            get {
                return ResourceManager.GetString("HoursOnCourtSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last match.
        /// </summary>
        public static string LastMatch {
            get {
                return ResourceManager.GetString("LastMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last 12 months.
        /// </summary>
        public static string LastTwelveMonths {
            get {
                return ResourceManager.GetString("LastTwelveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest break.
        /// </summary>
        public static string LongestBreak {
            get {
                return ResourceManager.GetString("LongestBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest streak.
        /// </summary>
        public static string LongestStreak {
            get {
                return ResourceManager.GetString("LongestStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match.
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches.
        /// </summary>
        public static string MatchesCount {
            get {
                return ResourceManager.GetString("MatchesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a court and your statistics will show up here..
        /// </summary>
        public static string NoPlayingData {
            get {
                return ResourceManager.GetString("NoPlayingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches yet.
        /// </summary>
        public static string NoPlayingDataTitle {
            get {
                return ResourceManager.GetString("NoPlayingDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not activated for this season..
        /// </summary>
        public static string NotActivatedForSeason {
            get {
                return ResourceManager.GetString("NotActivatedForSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal records.
        /// </summary>
        public static string PersonalRecords {
            get {
                return ResourceManager.GetString("PersonalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played on {0} of {1} days.
        /// </summary>
        public static string PlayedOnDays {
            get {
                return ResourceManager.GetString("PlayedOnDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon Ace.
        /// </summary>
        public static string PlayerType_AfternoonAce {
            get {
                return ResourceManager.GetString("PlayerType_AfternoonAce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You love playing between 12:00 and 17:00..
        /// </summary>
        public static string PlayerType_AfternoonAce_Description {
            get {
                return ResourceManager.GetString("PlayerType_AfternoonAce_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-Rounder.
        /// </summary>
        public static string PlayerType_AllRounder {
            get {
                return ResourceManager.GetString("PlayerType_AllRounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning, noon or night – you are always ready to play..
        /// </summary>
        public static string PlayerType_AllRounder_Description {
            get {
                return ResourceManager.GetString("PlayerType_AllRounder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Bird.
        /// </summary>
        public static string PlayerType_EarlyBird {
            get {
                return ResourceManager.GetString("PlayerType_EarlyBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of your matches start before noon..
        /// </summary>
        public static string PlayerType_EarlyBird_Description {
            get {
                return ResourceManager.GetString("PlayerType_EarlyBird_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Owl.
        /// </summary>
        public static string PlayerType_NightOwl {
            get {
                return ResourceManager.GetString("PlayerType_NightOwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of your matches start after 17:00..
        /// </summary>
        public static string PlayerType_NightOwl_Description {
            get {
                return ResourceManager.GetString("PlayerType_NightOwl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend Warrior.
        /// </summary>
        public static string PlayerType_WeekendWarrior {
            get {
                return ResourceManager.GetString("PlayerType_WeekendWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weekend belongs to tennis..
        /// </summary>
        public static string PlayerType_WeekendWarrior_Description {
            get {
                return ResourceManager.GetString("PlayerType_WeekendWarrior_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing since {0}.
        /// </summary>
        public static string PlayingSince {
            get {
                return ResourceManager.GetString("PlayingSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking limits.
        /// </summary>
        public static string PlayModeQuotas {
            get {
                return ResourceManager.GetString("PlayModeQuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play modes.
        /// </summary>
        public static string PlayModeUsage {
            get {
                return ResourceManager.GetString("PlayModeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left.
        /// </summary>
        public static string QuotaRemaining {
            get {
                return ResourceManager.GetString("QuotaRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your season {0}.
        /// </summary>
        public static string SeasonHeroTitle {
            get {
                return ResourceManager.GetString("SeasonHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seasons.
        /// </summary>
        public static string SeasonsPlayedChip {
            get {
                return ResourceManager.GetString("SeasonsPlayedChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season by season.
        /// </summary>
        public static string SeasonTrend {
            get {
                return ResourceManager.GetString("SeasonTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches and hours per season.
        /// </summary>
        public static string SeasonTrendSubtitle {
            get {
                return ResourceManager.GetString("SeasonTrendSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all {0} partners.
        /// </summary>
        public static string ShowAllPartners {
            get {
                return ResourceManager.GetString("ShowAllPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show less.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% vs. {1}.
        /// </summary>
        public static string TrendVs {
            get {
                return ResourceManager.GetString("TrendVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week of {0}.
        /// </summary>
        public static string WeekOf {
            get {
                return ResourceManager.GetString("WeekOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks.
        /// </summary>
        public static string WeeksCount {
            get {
                return ResourceManager.GetString("WeeksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a row with at least one match.
        /// </summary>
        public static string WeeksInARow {
            get {
                return ResourceManager.GetString("WeeksInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wks.
        /// </summary>
        public static string WeeksUnit {
            get {
                return ResourceManager.GetString("WeeksUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you play.
        /// </summary>
        public static string WhenYouPlay {
            get {
                return ResourceManager.GetString("WhenYouPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weekly and daily rhythm.
        /// </summary>
        public static string WhenYouPlaySubtitle {
            get {
                return ResourceManager.GetString("WhenYouPlaySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your play style.
        /// </summary>
        public static string YourPlayStyle {
            get {
                return ResourceManager.GetString("YourPlayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You vs. the club.
        /// </summary>
        public static string YouVsClub {
            get {
                return ResourceManager.GetString("YouVsClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches this season.
        /// </summary>
        public static string YouVsClubSubtitle {
            get {
                return ResourceManager.GetString("YouVsClubSubtitle", resourceCulture);
            }
        }
    }
}
