//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.Trophies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrophyLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrophyLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.Trophies.TrophyLocale", typeof(TrophyLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} badges.
        /// </summary>
        public static string BadgesCount {
            get {
                return ResourceManager.GetString("BadgesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge settings.
        /// </summary>
        public static string BadgeSettingsLink {
            get {
                return ResourceManager.GetString("BadgeSettingsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string BadgesTile {
            get {
                return ResourceManager.GetString("BadgesTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string EarnedDaysAgo {
            get {
                return ResourceManager.GetString("EarnedDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string EarnedToday {
            get {
                return ResourceManager.GetString("EarnedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string EarnedYesterday {
            get {
                return ResourceManager.GetString("EarnedYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play matches this season to earn your first badge – it will shine right here..
        /// </summary>
        public static string EmptyOwnText {
            get {
                return ResourceManager.GetString("EmptyOwnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trophies yet.
        /// </summary>
        public static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest level.
        /// </summary>
        public static string HighestLevelTile {
            get {
                return ResourceManager.GetString("HighestLevelTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} · Season {1}.
        /// </summary>
        public static string LevelInSeason {
            get {
                return ResourceManager.GetString("LevelInSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} reached.
        /// </summary>
        public static string LevelReached {
            get {
                return ResourceManager.GetString("LevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        public static string LevelShort {
            get {
                return ResourceManager.GetString("LevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 badge.
        /// </summary>
        public static string OneBadge {
            get {
                return ResourceManager.GetString("OneBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 season.
        /// </summary>
        public static string OneSeason {
            get {
                return ResourceManager.GetString("OneSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 special award.
        /// </summary>
        public static string OneSpecialAward {
            get {
                return ResourceManager.GetString("OneSpecialAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy case is private.
        /// </summary>
        public static string PrivateChip {
            get {
                return ResourceManager.GetString("PrivateChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} keeps the badges to themselves – maybe you will see them on court..
        /// </summary>
        public static string PrivateText {
            get {
                return ResourceManager.GetString("PrivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trophy case is private.
        /// </summary>
        public static string PrivateTitle {
            get {
                return ResourceManager.GetString("PrivateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member · {0}.
        /// </summary>
        public static string ProfileEyebrow {
            get {
                return ResourceManager.GetString("ProfileEyebrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seasons.
        /// </summary>
        public static string SeasonsCount {
            get {
                return ResourceManager.GetString("SeasonsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons with badges.
        /// </summary>
        public static string SeasonsTile {
            get {
                return ResourceManager.GetString("SeasonsTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string SeasonTitle {
            get {
                return ResourceManager.GetString("SeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special award.
        /// </summary>
        public static string SpecialAward {
            get {
                return ResourceManager.GetString("SpecialAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} special awards.
        /// </summary>
        public static string SpecialAwardsCount {
            get {
                return ResourceManager.GetString("SpecialAwardsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special awards.
        /// </summary>
        public static string SpecialAwardsTile {
            get {
                return ResourceManager.GetString("SpecialAwardsTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That's you.
        /// </summary>
        public static string ThisIsYou {
            get {
                return ResourceManager.GetString("ThisIsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top achievement.
        /// </summary>
        public static string TopAchievement {
            get {
                return ResourceManager.GetString("TopAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a badge to see the details.
        /// </summary>
        public static string TrophyCaseSubtitle {
            get {
                return ResourceManager.GetString("TrophyCaseSubtitle", resourceCulture);
            }
        }
    }
}
