//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.Legal {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LegalLocale {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LegalLocale() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.Legal.LegalLocale", typeof(LegalLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0}.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator details have not been configured yet (section "Legal" in wwwroot/appsettings.json)..
        /// </summary>
        public static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information according to § 5 E-Commerce Act (ECG) and § 25 Media Act (MedienG)..
        /// </summary>
        public static string Imprint_LegalBasis {
            get {
                return ResourceManager.GetString("Imprint_LegalBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Bookennis.
        /// </summary>
        public static string Imprint_PurposeTitle {
            get {
                return ResourceManager.GetString("Imprint_PurposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookennis is a free app for sports clubs to manage members and book courts. It is not a commercial offer and contains no.
        /// </summary>
        public static string Imprint_Purpose {
            get {
                return ResourceManager.GetString("Imprint_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content of the clubs.
        /// </summary>
        public static string Imprint_ClubContentTitle {
            get {
                return ResourceManager.GetString("Imprint_ClubContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clubs are responsible for the content they publish in Bookennis (e.g. events, emails, badges). Please contact your c.
        /// </summary>
        public static string Imprint_ClubContent {
            get {
                return ResourceManager.GetString("Imprint_ClubContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability for links.
        /// </summary>
        public static string Imprint_LiabilityTitle {
            get {
                return ResourceManager.GetString("Imprint_LiabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despite careful checks we accept no liability for the content of external links. The operators of the linked pages are s.
        /// </summary>
        public static string Imprint_Liability {
            get {
                return ResourceManager.GetString("Imprint_Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protecting your data is important to us. This privacy policy explains which personal data Bookennis processes, why, and .
        /// </summary>
        public static string Privacy_Intro {
            get {
                return ResourceManager.GetString("Privacy_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Controller.
        /// </summary>
        public static string Privacy_Controller_Title {
            get {
                return ResourceManager.GetString("Privacy_Controller_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller within the meaning of the General Data Protection Regulation (GDPR) is:.
        /// </summary>
        public static string Privacy_Controller_Body {
            get {
                return ResourceManager.GetString("Privacy_Controller_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Which data we process.
        /// </summary>
        public static string Privacy_Data_Title {
            get {
                return ResourceManager.GetString("Privacy_Data_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Account: first and last name, email address, date of birth, gender, language, password (stored only as a secure hash),.
        /// </summary>
        public static string Privacy_Data_Body {
            get {
                return ResourceManager.GetString("Privacy_Data_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Purposes and legal basis.
        /// </summary>
        public static string Privacy_Purpose_Title {
            get {
                return ResourceManager.GetString("Privacy_Purpose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Providing the app (account, club membership, booking, events, emails such as confirmations and booking notifications):.
        /// </summary>
        public static string Privacy_Purpose_Body {
            get {
                return ResourceManager.GetString("Privacy_Purpose_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Who can see your data.
        /// </summary>
        public static string Privacy_Recipients_Title {
            get {
                return ResourceManager.GetString("Privacy_Recipients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Your club: the club's administrators and officials see your member data (e.g. name, contact details, date of birth, bo.
        /// </summary>
        public static string Privacy_Recipients_Body {
            get {
                return ResourceManager.GetString("Privacy_Recipients_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Children.
        /// </summary>
        public static string Privacy_Children_Title {
            get {
                return ResourceManager.GetString("Privacy_Children_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles of children are created and managed by their parents, who are responsible for the data they enter. Children und.
        /// </summary>
        public static string Privacy_Children_Body {
            get {
                return ResourceManager.GetString("Privacy_Children_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Cookies and local storage.
        /// </summary>
        public static string Privacy_Cookies_Title {
            get {
                return ResourceManager.GetString("Privacy_Cookies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookennis only uses a technically necessary cookie that keeps you signed in, and stores display settings (e.g. dark mode.
        /// </summary>
        public static string Privacy_Cookies_Body {
            get {
                return ResourceManager.GetString("Privacy_Cookies_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. How long we keep your data.
        /// </summary>
        public static string Privacy_Retention_Title {
            get {
                return ResourceManager.GetString("Privacy_Retention_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We keep your data as long as you have an account. When you leave a club, your membership in that club is deleted. When y.
        /// </summary>
        public static string Privacy_Retention_Body {
            get {
                return ResourceManager.GetString("Privacy_Retention_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Your rights.
        /// </summary>
        public static string Privacy_Rights_Title {
            get {
                return ResourceManager.GetString("Privacy_Rights_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the right to access, rectification, erasure, restriction of processing, data portability and to object to the p.
        /// </summary>
        public static string Privacy_Rights_Body {
            get {
                return ResourceManager.GetString("Privacy_Rights_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Right to lodge a complaint.
        /// </summary>
        public static string Privacy_Complaint_Title {
            get {
                return ResourceManager.GetString("Privacy_Complaint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe that the processing of your data violates data protection law, you can lodge a complaint with a superviso.
        /// </summary>
        public static string Privacy_Complaint_Body {
            get {
                return ResourceManager.GetString("Privacy_Complaint_Body", resourceCulture);
            }
        }
    }
}
