//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.Account.AccountLocale", typeof(AccountLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is required.
        /// </summary>
        public static string BirthdayValidation {
            get {
                return ResourceManager.GetString("BirthdayValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in as guest.
        /// </summary>
        public static string ConfirmGuestLoginSuccess {
            get {
                return ResourceManager.GetString("ConfirmGuestLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address must be valid.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string FirstnameValidation {
            get {
                return ResourceManager.GetString("FirstnameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest login.
        /// </summary>
        public static string GuestLogin {
            get {
                return ResourceManager.GetString("GuestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastnameValidation {
            get {
                return ResourceManager.GetString("LastnameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain at least one digit.
        /// </summary>
        public static string MustContainDigit {
            get {
                return ResourceManager.GetString("MustContainDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain lower case letter.
        /// </summary>
        public static string MustContainLower {
            get {
                return ResourceManager.GetString("MustContainLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain a special symbol. Allowed characters: *.!@#$%^&amp;(){}[]:;&lt;&gt;,.?/~`_+-=|\.
        /// </summary>
        public static string MustContainSpecial {
            get {
                return ResourceManager.GetString("MustContainSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain upper case letter.
        /// </summary>
        public static string MustContainUpper {
            get {
                return ResourceManager.GetString("MustContainUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        public static string Password2Validation {
            get {
                return ResourceManager.GetString("Password2Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to be within 8 and 50 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reset password email.
        /// </summary>
        public static string SendResetEmail {
            get {
                return ResourceManager.GetString("SendResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club management &amp; court booking for every club.
        /// </summary>
        public static string Pitch_Headline {
            get {
                return ResourceManager.GetString("Pitch_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookennis brings your whole club together: members book courts online, and the board manages members[rest of string was truncated].
        /// </summary>
        public static string Pitch_Lead {
            get {
                return ResourceManager.GetString("Pitch_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% free.
        /// </summary>
        public static string Pitch_FreeBadge {
            get {
                return ResourceManager.GetString("Pitch_FreeBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free to use for clubs and members. No fees, no subscriptions, no hidden costs..
        /// </summary>
        public static string Pitch_FreeText {
            get {
                return ResourceManager.GetString("Pitch_FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online court booking.
        /// </summary>
        public static string Pitch_Feature_Booking {
            get {
                return ResourceManager.GetString("Pitch_Feature_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book courts in seconds – including recurring bookings..
        /// </summary>
        public static string Pitch_Feature_Booking_Description {
            get {
                return ResourceManager.GetString("Pitch_Feature_Booking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members &amp; seasons.
        /// </summary>
        public static string Pitch_Feature_Members {
            get {
                return ResourceManager.GetString("Pitch_Feature_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage members, families, roles and seasons..
        /// </summary>
        public static string Pitch_Feature_Members_Description {
            get {
                return ResourceManager.GetString("Pitch_Feature_Members_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest cards.
        /// </summary>
        public static string Pitch_Feature_Guests {
            get {
                return ResourceManager.GetString("Pitch_Feature_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let guests book with a simple link or code..
        /// </summary>
        public static string Pitch_Feature_Guests_Description {
            get {
                return ResourceManager.GetString("Pitch_Feature_Guests_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics &amp; leaderboards.
        /// </summary>
        public static string Pitch_Feature_Statistics {
            get {
                return ResourceManager.GetString("Pitch_Feature_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how busy your courts are and who plays the most..
        /// </summary>
        public static string Pitch_Feature_Statistics_Description {
            get {
                return ResourceManager.GetString("Pitch_Feature_Statistics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges &amp; trophies.
        /// </summary>
        public static string Pitch_Feature_Badges {
            get {
                return ResourceManager.GetString("Pitch_Feature_Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward active players with badges every season..
        /// </summary>
        public static string Pitch_Feature_Badges_Description {
            get {
                return ResourceManager.GetString("Pitch_Feature_Badges_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to book courts and see what's happening in your club..
        /// </summary>
        public static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to Bookennis?.
        /// </summary>
        public static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a free account.
        /// </summary>
        public static string CreateFreeAccount {
            get {
                return ResourceManager.GetString("CreateFreeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your free account.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It only takes a minute. Afterwards you can join your club and start booking..
        /// </summary>
        public static string Register_Subtitle {
            get {
                return ResourceManager.GetString("Register_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About you.
        /// </summary>
        public static string Register_AboutYou {
            get {
                return ResourceManager.GetString("Register_AboutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login details.
        /// </summary>
        public static string Register_LoginDetails {
            get {
                return ResourceManager.GetString("Register_LoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We'll send you a link to confirm this address..
        /// </summary>
        public static string Register_EmailHelper {
            get {
                return ResourceManager.GetString("Register_EmailHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your club may need your address for its member list. You can also add it later in your profile..
        /// </summary>
        public static string Register_AddressHint {
            get {
                return ResourceManager.GetString("Register_AddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free forever – no credit card required..
        /// </summary>
        public static string Register_FreeHint {
            get {
                return ResourceManager.GetString("Register_FreeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Register_HaveAccount {
            get {
                return ResourceManager.GetString("Register_HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a confirmation link to {0}. Click the link in the email to activate your account, then log i[rest of string was truncated].
        /// </summary>
        public static string Register_CheckInbox {
            get {
                return ResourceManager.GetString("Register_CheckInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your inbox.
        /// </summary>
        public static string CheckInbox_Title {
            get {
                return ResourceManager.GetString("CheckInbox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email after a few minutes? Please check your spam folder..
        /// </summary>
        public static string CheckInbox_Spam {
            get {
                return ResourceManager.GetString("CheckInbox_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 to 50 characters.
        /// </summary>
        public static string Requirement_Length {
            get {
                return ResourceManager.GetString("Requirement_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain a special character.
        /// </summary>
        public static string Requirement_Special {
            get {
                return ResourceManager.GetString("Requirement_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem. Enter the email address of your account and we'll send you a link to choose a new passwo[rest of string was truncated].
        /// </summary>
        public static string ForgotPassword_Subtitle {
            get {
                return ResourceManager.GetString("ForgotPassword_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an account exists for {0}, we just sent it a link to reset the password..
        /// </summary>
        public static string ForgotPassword_CheckInbox {
            get {
                return ResourceManager.GetString("ForgotPassword_CheckInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the email from Bookennis..
        /// </summary>
        public static string ForgotPassword_Step1 {
            get {
                return ResourceManager.GetString("ForgotPassword_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link – it is valid for 24 hours..
        /// </summary>
        public static string ForgotPassword_Step2 {
            get {
                return ResourceManager.GetString("ForgotPassword_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new password and log in..
        /// </summary>
        public static string ForgotPassword_Step3 {
            get {
                return ResourceManager.GetString("ForgotPassword_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the email again.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again in {0}s.
        /// </summary>
        public static string ResendIn {
            get {
                return ResourceManager.GetString("ResendIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent the email again..
        /// </summary>
        public static string ResendSuccess {
            get {
                return ResourceManager.GetString("ResendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a different email address.
        /// </summary>
        public static string UseDifferentEmail {
            get {
                return ResourceManager.GetString("UseDifferentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new password.
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0}.
        /// </summary>
        public static string ResetPassword_Subtitle {
            get {
                return ResourceManager.GetString("ResetPassword_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link doesn't work.
        /// </summary>
        public static string ResetPassword_InvalidTitle {
            get {
                return ResourceManager.GetString("ResetPassword_InvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link to reset your password is incomplete. Please use the link from the email or request a new o[rest of string was truncated].
        /// </summary>
        public static string ResetPassword_InvalidText {
            get {
                return ResourceManager.GetString("ResetPassword_InvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string ResetPassword_SuccessTitle {
            get {
                return ResourceManager.GetString("ResetPassword_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password is set. You can now log in with it..
        /// </summary>
        public static string ResetPassword_SuccessText {
            get {
                return ResourceManager.GetString("ResetPassword_SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a new link.
        /// </summary>
        public static string RequestNewLink {
            get {
                return ResourceManager.GetString("RequestNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new password.
        /// </summary>
        public static string SaveNewPassword {
            get {
                return ResourceManager.GetString("SaveNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming your email address....
        /// </summary>
        public static string ConfirmEmailProcessing {
            get {
                return ResourceManager.GetString("ConfirmEmailProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You're all set!.
        /// </summary>
        public static string ConfirmEmail_SuccessTitle {
            get {
                return ResourceManager.GetString("ConfirmEmail_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is confirmed. Log in to join your club and book your first court..
        /// </summary>
        public static string ConfirmEmail_SuccessText {
            get {
                return ResourceManager.GetString("ConfirmEmail_SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation failed.
        /// </summary>
        public static string ConfirmEmail_FailedTitle {
            get {
                return ResourceManager.GetString("ConfirmEmail_FailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation link is invalid or has expired. If you already confirmed your email, simply log in.[rest of string was truncated].
        /// </summary>
        public static string ConfirmEmail_FailedText {
            get {
                return ResourceManager.GetString("ConfirmEmail_FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ConfirmEmail_ResetInstead {
            get {
                return ResourceManager.GetString("ConfirmEmail_ResetInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address changed.
        /// </summary>
        public static string ConfirmEmailChange_SuccessTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From now on, log in with {0}..
        /// </summary>
        public static string ConfirmEmailChange_SuccessText {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not changed.
        /// </summary>
        public static string ConfirmEmailChange_FailedTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_FailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop photo.
        /// </summary>
        public static string CropPhoto {
            get {
                return ResourceManager.GetString("CropPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How other members see you.
        /// </summary>
        public static string Profile_GeneralInfoSubtitle {
            get {
                return ResourceManager.GetString("Profile_GeneralInfoSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional – only visible to your club's board.
        /// </summary>
        public static string Profile_AddressSubtitle {
            get {
                return ResourceManager.GetString("Profile_AddressSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been saved..
        /// </summary>
        public static string Profile_Saved {
            get {
                return ResourceManager.GetString("Profile_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login &amp; security.
        /// </summary>
        public static string Security_Title {
            get {
                return ResourceManager.GetString("Security_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login email and password.
        /// </summary>
        public static string Security_Subtitle {
            get {
                return ResourceManager.GetString("Security_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We'll send a confirmation link to your new address. Your email address only changes after you click [rest of string was truncated].
        /// </summary>
        public static string ChangeEmail_Description {
            get {
                return ResourceManager.GetString("ChangeEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your security, please confirm with your password..
        /// </summary>
        public static string ChangeEmail_PasswordHelper {
            get {
                return ResourceManager.GetString("ChangeEmail_PasswordHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for confirmation: open the link we sent to {0}..
        /// </summary>
        public static string ChangeEmail_Pending {
            get {
                return ResourceManager.GetString("ChangeEmail_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation link sent to {0}..
        /// </summary>
        public static string ChangeEmail_Sent {
            get {
                return ResourceManager.GetString("ChangeEmail_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current email address.
        /// </summary>
        public static string CurrentEmail {
            get {
                return ResourceManager.GetString("CurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email address.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send confirmation link.
        /// </summary>
        public static string SendConfirmationLink {
            get {
                return ResourceManager.GetString("SendConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the.
        /// </summary>
        public static string Register_PrivacyConsent_Before {
            get {
                return ResourceManager.GetString("Register_PrivacyConsent_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string Register_PrivacyConsent_Link {
            get {
                return ResourceManager.GetString("Register_PrivacyConsent_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and agree to my data being processed as described there..
        /// </summary>
        public static string Register_PrivacyConsent_After {
            get {
                return ResourceManager.GetString("Register_PrivacyConsent_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you have read the privacy policy..
        /// </summary>
        public static string Register_PrivacyConsent_Validation {
            get {
                return ResourceManager.GetString("Register_PrivacyConsent_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data.
        /// </summary>
        public static string Data_Title {
            get {
                return ResourceManager.GetString("Data_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what Bookennis stores about you.
        /// </summary>
        public static string Data_Subtitle {
            get {
                return ResourceManager.GetString("Data_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data export.
        /// </summary>
        public static string Data_Export {
            get {
                return ResourceManager.GetString("Data_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your data as a file (JSON).
        /// </summary>
        public static string Data_ExportDescription {
            get {
                return ResourceManager.GetString("Data_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Data_Download {
            get {
                return ResourceManager.GetString("Data_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Data_Privacy {
            get {
                return ResourceManager.GetString("Data_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How we handle your data.
        /// </summary>
        public static string Data_PrivacyDescription {
            get {
                return ResourceManager.GetString("Data_PrivacyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Data_Open {
            get {
                return ResourceManager.GetString("Data_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave &amp; delete.
        /// </summary>
        public static string Danger_Title {
            get {
                return ResourceManager.GetString("Danger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These actions can't be undone.
        /// </summary>
        public static string Danger_Subtitle {
            get {
                return ResourceManager.GetString("Danger_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave club.
        /// </summary>
        public static string LeaveClub {
            get {
                return ResourceManager.GetString("LeaveClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string LeaveClub_Button {
            get {
                return ResourceManager.GetString("LeaveClub_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave {0}? Your membership, your booking history, badges and event registrations in this club will.
        /// </summary>
        public static string LeaveClub_Confirm {
            get {
                return ResourceManager.GetString("LeaveClub_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have left {0}..
        /// </summary>
        public static string LeaveClub_Success {
            get {
                return ResourceManager.GetString("LeaveClub_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes your account and all your data for good.
        /// </summary>
        public static string DeleteAccount_Description {
            get {
                return ResourceManager.GetString("DeleteAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAccount_Button {
            get {
                return ResourceManager.GetString("DeleteAccount_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete for good.
        /// </summary>
        public static string DeleteAccount_Confirm {
            get {
                return ResourceManager.GetString("DeleteAccount_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be deleted immediately and can't be restored..
        /// </summary>
        public static string DeleteAccount_Warning {
            get {
                return ResourceManager.GetString("DeleteAccount_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile, profile picture, subscription plans and all your bookings, badges and event registrations are deleted..
        /// </summary>
        public static string DeleteAccount_Consequence_Data {
            get {
                return ResourceManager.GetString("DeleteAccount_Consequence_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You leave all your clubs. Upcoming bookings in which you play alone are cancelled..
        /// </summary>
        public static string DeleteAccount_Consequence_Clubs {
            get {
                return ResourceManager.GetString("DeleteAccount_Consequence_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children you created are handed over to the other parent, or deleted as well if there is none..
        /// </summary>
        public static string DeleteAccount_Consequence_Children {
            get {
                return ResourceManager.GetString("DeleteAccount_Consequence_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: download your data first if you want to keep a copy..
        /// </summary>
        public static string DeleteAccount_ExportHint {
            get {
                return ResourceManager.GetString("DeleteAccount_ExportHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted..
        /// </summary>
        public static string DeleteAccount_Success {
            get {
                return ResourceManager.GetString("DeleteAccount_Success", resourceCulture);
            }
        }
    }
}
