//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.Members {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MembersAdminLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MembersAdminLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.Members.MembersAdminLocale", typeof(MembersAdminLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} this season.
        /// </summary>
        public static string ActiveChip {
            get {
                return ResourceManager.GetString("ActiveChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age group.
        /// </summary>
        public static string AgeGroup {
            get {
                return ResourceManager.GetString("AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults (18–34).
        /// </summary>
        public static string AgeGroup_Adults {
            get {
                return ResourceManager.GetString("AgeGroup_Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids (≤ 12).
        /// </summary>
        public static string AgeGroup_Kids {
            get {
                return ResourceManager.GetString("AgeGroup_Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniors (35+).
        /// </summary>
        public static string AgeGroup_Seniors {
            get {
                return ResourceManager.GetString("AgeGroup_Seniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teenagers (13–17).
        /// </summary>
        public static string AgeGroup_Teenagers {
            get {
                return ResourceManager.GetString("AgeGroup_Teenagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        public static string AgeYears {
            get {
                return ResourceManager.GetString("AgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string BackToMembers {
            get {
                return ResourceManager.GetString("BackToMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings per week.
        /// </summary>
        public static string BookingsPerWeek {
            get {
                return ResourceManager.GetString("BookingsPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many upcoming bookings the member may have at the same time.
        /// </summary>
        public static string BookingsPerWeekHint {
            get {
                return ResourceManager.GetString("BookingsPerWeekHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current list.
        /// </summary>
        public static string CopyCaption {
            get {
                return ResourceManager.GetString("CopyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separated by commas.
        /// </summary>
        public static string CopyComma {
            get {
                return ResourceManager.GetString("CopyComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy email.
        /// </summary>
        public static string CopyEmail {
            get {
                return ResourceManager.GetString("CopyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy emails.
        /// </summary>
        public static string CopyEmails {
            get {
                return ResourceManager.GetString("CopyEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One per line.
        /// </summary>
        public static string CopyLines {
            get {
                return ResourceManager.GetString("CopyLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separated by semicolons (Outlook).
        /// </summary>
        public static string CopySemicolon {
            get {
                return ResourceManager.GetString("CopySemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the emails of all members.
        /// </summary>
        public static string CopyTextAll {
            get {
                return ResourceManager.GetString("CopyTextAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the emails of all members matching the filter.
        /// </summary>
        public static string CopyTextFiltered {
            get {
                return ResourceManager.GetString("CopyTextFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit member.
        /// </summary>
        public static string EditMember {
            get {
                return ResourceManager.GetString("EditMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Email_Any {
            get {
                return ResourceManager.GetString("Email_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With email.
        /// </summary>
        public static string Email_With {
            get {
                return ResourceManager.GetString("Email_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without email.
        /// </summary>
        public static string Email_Without {
            get {
                return ResourceManager.GetString("Email_Without", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email copied.
        /// </summary>
        public static string EmailCopied {
            get {
                return ResourceManager.GetString("EmailCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} emails copied to the clipboard.
        /// </summary>
        public static string EmailsCopied {
            get {
                return ResourceManager.GetString("EmailsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} emails copied – {1} members have no email or share one.
        /// </summary>
        public static string EmailsCopiedWithMissing {
            get {
                return ResourceManager.GetString("EmailsCopiedWithMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enrolled.
        /// </summary>
        public static string Enrolled {
            get {
                return ResourceManager.GetString("Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled {0}.
        /// </summary>
        public static string EnrolledChip {
            get {
                return ResourceManager.GetString("EnrolledChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diverse.
        /// </summary>
        public static string Gender_Diverse {
            get {
                return ResourceManager.GetString("Gender_Diverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not back yet.
        /// </summary>
        public static string LapsedChip {
            get {
                return ResourceManager.GetString("LapsedChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last played.
        /// </summary>
        public static string LastPlayed {
            get {
                return ResourceManager.GetString("LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches.
        /// </summary>
        public static string MatchesShort {
            get {
                return ResourceManager.GetString("MatchesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches this season.
        /// </summary>
        public static string MatchesThisSeason {
            get {
                return ResourceManager.GetString("MatchesThisSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member · {0}.
        /// </summary>
        public static string MemberEyebrow {
            get {
                return ResourceManager.GetString("MemberEyebrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was saved.
        /// </summary>
        public static string MemberSaved {
            get {
                return ResourceManager.GetString("MemberSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        public static string MembersChip {
            get {
                return ResourceManager.GetString("MembersChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members found.
        /// </summary>
        public static string MembersFound {
            get {
                return ResourceManager.GetString("MembersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since {0}.
        /// </summary>
        public static string MemberSinceChip {
            get {
                return ResourceManager.GetString("MemberSinceChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find members, check their seasons and copy emails for your mailings.
        /// </summary>
        public static string MembersSubtitle {
            get {
                return ResourceManager.GetString("MembersSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a month ago.
        /// </summary>
        public static string MonthAgo {
            get {
                return ResourceManager.GetString("MonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never played.
        /// </summary>
        public static string NeverPlayed {
            get {
                return ResourceManager.GetString("NeverPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new.
        /// </summary>
        public static string NewChip {
            get {
                return ResourceManager.GetString("NewChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No booking in {0}.
        /// </summary>
        public static string NoBookingsInSeasonChip {
            get {
                return ResourceManager.GetString("NoBookingsInSeasonChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email.
        /// </summary>
        public static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of these members has an email address..
        /// </summary>
        public static string NoEmailsToCopy {
            get {
                return ResourceManager.GetString("NoEmailsToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members match these filters..
        /// </summary>
        public static string NoMembersFound {
            get {
                return ResourceManager.GetString("NoMembersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seasons yet – create one in the club settings..
        /// </summary>
        public static string NoSeasons {
            get {
                return ResourceManager.GetString("NoSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not enrolled.
        /// </summary>
        public static string NotEnrolled {
            get {
                return ResourceManager.GetString("NotEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enrolled {0}.
        /// </summary>
        public static string NotEnrolledChip {
            get {
                return ResourceManager.GetString("NotEnrolledChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email of a parent.
        /// </summary>
        public static string ParentEmail {
            get {
                return ResourceManager.GetString("ParentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per page.
        /// </summary>
        public static string PerPage {
            get {
                return ResourceManager.GetString("PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per week.
        /// </summary>
        public static string PerWeek {
            get {
                return ResourceManager.GetString("PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing since {0}.
        /// </summary>
        public static string PlayingSinceHint {
            get {
                return ResourceManager.GetString("PlayingSinceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This season.
        /// </summary>
        public static string PresetActive {
            get {
                return ResourceManager.GetString("PresetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last season, not this one.
        /// </summary>
        public static string PresetLapsed {
            get {
                return ResourceManager.GetString("PresetLapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last season.
        /// </summary>
        public static string PresetLastSeason {
            get {
                return ResourceManager.GetString("PresetLastSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New this season.
        /// </summary>
        public static string PresetNew {
            get {
                return ResourceManager.GetString("PresetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled but never played.
        /// </summary>
        public static string PresetNoBookings {
            get {
                return ResourceManager.GetString("PresetNoBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enrolled this season.
        /// </summary>
        public static string PresetNotEnrolled {
            get {
                return ResourceManager.GetString("PresetNotEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without email.
        /// </summary>
        public static string PresetWithoutEmail {
            get {
                return ResourceManager.GetString("PresetWithoutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick edit.
        /// </summary>
        public static string QuickEdit {
            get {
                return ResourceManager.GetString("QuickEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick filters.
        /// </summary>
        public static string QuickFilters {
            get {
                return ResourceManager.GetString("QuickFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}–{1} of {2}.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        public static string ResultCount {
            get {
                return ResourceManager.GetString("ResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member needs at least one role..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles control what the member may do in the club.
        /// </summary>
        public static string RolesHint {
            get {
                return ResourceManager.GetString("RolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name or email.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string SeasonEnrollment {
            get {
                return ResourceManager.GetString("SeasonEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members can only book in seasons they are enrolled in.
        /// </summary>
        public static string SeasonEnrollmentHint {
            get {
                return ResourceManager.GetString("SeasonEnrollmentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any – tap to only show enrolled members.
        /// </summary>
        public static string SeasonRule_Any {
            get {
                return ResourceManager.GetString("SeasonRule_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled – tap to only show members that are not enrolled.
        /// </summary>
        public static string SeasonRule_In {
            get {
                return ResourceManager.GetString("SeasonRule_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enrolled – tap to remove the filter.
        /// </summary>
        public static string SeasonRule_NotIn {
            get {
                return ResourceManager.GetString("SeasonRule_NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons enrolled.
        /// </summary>
        public static string SeasonsEnrolled {
            get {
                return ResourceManager.GetString("SeasonsEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string SeasonsFilter {
            get {
                return ResourceManager.GetString("SeasonsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a season: ✓ enrolled, ✕ not enrolled – e.g. ✓ last season and ✕ this season shows who has not co[rest of string was truncated]&quot;.
        /// </summary>
        public static string SeasonsFilterHint {
            get {
                return ResourceManager.GetString("SeasonsFilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Sort_Birthday {
            get {
                return ResourceManager.GetString("Sort_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Sort_ContactEmail {
            get {
                return ResourceManager.GetString("Sort_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Sort_FirstName {
            get {
                return ResourceManager.GetString("Sort_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Sort_LastName {
            get {
                return ResourceManager.GetString("Sort_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last played.
        /// </summary>
        public static string Sort_LastPlayed {
            get {
                return ResourceManager.GetString("Sort_LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change sort direction.
        /// </summary>
        public static string SortDirection {
            get {
                return ResourceManager.GetString("SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours on court.
        /// </summary>
        public static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string TotalMatches {
            get {
                return ResourceManager.GetString("TotalMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + {0} upcoming.
        /// </summary>
        public static string UpcomingHint {
            get {
                return ResourceManager.GetString("UpcomingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a year ago.
        /// </summary>
        public static string YearAgo {
            get {
                return ResourceManager.GetString("YearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs..
        /// </summary>
        public static string YearsShort {
            get {
                return ResourceManager.GetString("YearsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
