//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.Calendar {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarLocale {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarLocale() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.Calendar.CalendarLocale", typeof(CalendarLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About this event.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add option.
        /// </summary>
        public static string AddOption {
            get {
                return ResourceManager.GetString("AddOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members enter a number per option, e.g. 2x Schnitzel, 1x Veggie..
        /// </summary>
        public static string AllowQuantitiesHint {
            get {
                return ResourceManager.GetString("AllowQuantitiesHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to With quantities.
        /// </summary>
        public static string AllowQuantitiesLabel {
            get {
                return ResourceManager.GetString("AllowQuantitiesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string BackToCalendar {
            get {
                return ResourceManager.GetString("BackToCalendar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to event.
        /// </summary>
        public static string BackToEvent {
            get {
                return ResourceManager.GetString("BackToEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} places.
        /// </summary>
        public static string CapacityLabel {
            get {
                return ResourceManager.GetString("CapacityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string Category_Meeting {
            get {
                return ResourceManager.GetString("Category_Meeting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Category_Other {
            get {
                return ResourceManager.GetString("Category_Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Category_Social {
            get {
                return ResourceManager.GetString("Category_Social", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string Category_Tournament {
            get {
                return ResourceManager.GetString("Category_Tournament", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work effort.
        /// </summary>
        public static string Category_WorkEffort {
            get {
                return ResourceManager.GetString("Category_WorkEffort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment (optional).
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. I'll bring a cake.
        /// </summary>
        public static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create event.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ddd, d MMM.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ddd, d MMM yyyy.
        /// </summary>
        public static string DateFormatWithYear {
            get {
                return ResourceManager.GetString("DateFormatWithYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration deadline (optional).
        /// </summary>
        public static string DeadlineDateLabel {
            get {
                return ResourceManager.GetString("DeadlineDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Without a time it ends at 23:59.
        /// </summary>
        public static string DeadlineHint {
            get {
                return ResourceManager.GetString("DeadlineHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration closed on {0}.
        /// </summary>
        public static string DeadlinePassed {
            get {
                return ResourceManager.GetString("DeadlinePassed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deadline time.
        /// </summary>
        public static string DeadlineTimeLabel {
            get {
                return ResourceManager.GetString("DeadlineTimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete event.
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete "{0}"?.
        /// </summary>
        public static string DeleteEventConfirm {
            get {
                return ResourceManager.GetString("DeleteEventConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete "{0}"? The {1} registrations will be deleted as well..
        /// </summary>
        public static string DeleteEventConfirmWithRegistrations {
            get {
                return ResourceManager.GetString("DeleteEventConfirmWithRegistrations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete option.
        /// </summary>
        public static string DeleteOption {
            get {
                return ResourceManager.GetString("DeleteOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete question.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What is planned, what should people bring?.
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        public static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last day.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End time (optional).
        /// </summary>
        public static string EndTimeLabel {
            get {
                return ResourceManager.GetString("EndTimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} events.
        /// </summary>
        public static string EventCount {
            get {
                return ResourceManager.GetString("EventCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} event.
        /// </summary>
        public static string EventCountOne {
            get {
                return ResourceManager.GetString("EventCountOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event created.
        /// </summary>
        public static string EventCreated {
            get {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event deleted.
        /// </summary>
        public static string EventDeleted {
            get {
                return ResourceManager.GetString("EventDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event details.
        /// </summary>
        public static string EventDetails {
            get {
                return ResourceManager.GetString("EventDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This event is fully booked..
        /// </summary>
        public static string EventIsFull {
            get {
                return ResourceManager.GetString("EventIsFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This event is over..
        /// </summary>
        public static string EventIsOver {
            get {
                return ResourceManager.GetString("EventIsOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This event does not exist (anymore)..
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event saved.
        /// </summary>
        public static string EventSaved {
            get {
                return ResourceManager.GetString("EventSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export participants (Excel).
        /// </summary>
        public static string ExportParticipants {
            get {
                return ResourceManager.GetString("ExportParticipants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to from {0}.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Including yourself.
        /// </summary>
        public static string HeadCountHint {
            get {
                return ResourceManager.GetString("HeadCountHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How many people are coming?.
        /// </summary>
        public static string HeadCountLabel {
            get {
                return ResourceManager.GetString("HeadCountLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work efforts, parties and get-togethers of the club at a glance..
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Club calendar.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In {0} days.
        /// </summary>
        public static string InDays {
            get {
                return ResourceManager.GetString("InDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E.g. meals: the quantities can't exceed the number of people of a registration..
        /// </summary>
        public static string LimitQuantityHint {
            get {
                return ResourceManager.GetString("LimitQuantityHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At most one per person.
        /// </summary>
        public static string LimitQuantityLabel {
            get {
                return ResourceManager.GetString("LimitQuantityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link copied – paste it into WhatsApp or anywhere else..
        /// </summary>
        public static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location (optional).
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Clubhouse.
        /// </summary>
        public static string LocationPlaceholder {
            get {
                return ResourceManager.GetString("LocationPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total number of people incl. companions.
        /// </summary>
        public static string MaxParticipantsHint {
            get {
                return ResourceManager.GetString("MaxParticipantsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max. participants (optional).
        /// </summary>
        public static string MaxParticipantsLabel {
            get {
                return ResourceManager.GetString("MaxParticipantsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple days.
        /// </summary>
        public static string MultiDay {
            get {
                return ResourceManager.GetString("MultiDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ☑️ Multiple choice.
        /// </summary>
        public static string MultipleChoice {
            get {
                return ResourceManager.GetString("MultipleChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select all that apply.
        /// </summary>
        public static string MultipleChoiceHint {
            get {
                return ResourceManager.GetString("MultipleChoiceHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing planned yet.
        /// </summary>
        public static string MyClubEventsEmptySubtitle {
            get {
                return ResourceManager.GetString("MyClubEventsEmptySubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What's coming up in the club.
        /// </summary>
        public static string MyClubEventsSubtitle {
            get {
                return ResourceManager.GetString("MyClubEventsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New event.
        /// </summary>
        public static string NewEvent {
            get {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        public static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next up.
        /// </summary>
        public static string NextUp {
            get {
                return ResourceManager.GetString("NextUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No events this month..
        /// </summary>
        public static string NoEventsInMonth {
            get {
                return ResourceManager.GetString("NoEventsInMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No events on this day..
        /// </summary>
        public static string NoEventsOnDay {
            get {
                return ResourceManager.GetString("NoEventsOnDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nobody has registered yet. Be the first!.
        /// </summary>
        public static string NoParticipantsYet {
            get {
                return ResourceManager.GetString("NoParticipantsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No past events in the last year..
        /// </summary>
        public static string NoPastEvents {
            get {
                return ResourceManager.GetString("NoPastEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No registration needed – just come along!.
        /// </summary>
        public static string NoRegistrationNeeded {
            get {
                return ResourceManager.GetString("NoRegistrationNeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No events planned yet..
        /// </summary>
        public static string NoUpcomingEvents {
            get {
                return ResourceManager.GetString("NoUpcomingEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only maintainers, (youth) sports directors and admins can plan events..
        /// </summary>
        public static string NotAllowedToManage {
            get {
                return ResourceManager.GetString("NotAllowedToManage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing planned yet.
        /// </summary>
        public static string NothingPlanned {
            get {
                return ResourceManager.GetString("NothingPlanned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option {0}.
        /// </summary>
        public static string OptionLabel {
            get {
                return ResourceManager.GetString("OptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organized by {0}.
        /// </summary>
        public static string OrganizedBy {
            get {
                return ResourceManager.GetString("OrganizedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organizer actions.
        /// </summary>
        public static string OrganizerActions {
            get {
                return ResourceManager.GetString("OrganizerActions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        public static string Past {
            get {
                return ResourceManager.GetString("Past", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Past events.
        /// </summary>
        public static string PastEvents {
            get {
                return ResourceManager.GetString("PastEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} people.
        /// </summary>
        public static string PeopleCount {
            get {
                return ResourceManager.GetString("PeopleCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} person.
        /// </summary>
        public static string PeopleCountOne {
            get {
                return ResourceManager.GetString("PeopleCountOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to people.
        /// </summary>
        public static string PeopleUnit {
            get {
                return ResourceManager.GetString("PeopleUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to person.
        /// </summary>
        public static string PersonUnit {
            get {
                return ResourceManager.GetString("PersonUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} more places available.
        /// </summary>
        public static string PlacesLeft {
            get {
                return ResourceManager.GetString("PlacesLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please answer "{0}"..
        /// </summary>
        public static string PleaseAnswer {
            get {
                return ResourceManager.GetString("PleaseAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        public static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How many of your {0} people?.
        /// </summary>
        public static string QuantityHint {
            get {
                return ResourceManager.GetString("QuantityHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How many?.
        /// </summary>
        public static string QuantityHintUnlimited {
            get {
                return ResourceManager.GetString("QuantityHintUnlimited", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QuestionLabel {
            get {
                return ResourceManager.GetString("QuestionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Staying for food?.
        /// </summary>
        public static string QuestionPlaceholder {
            get {
                return ResourceManager.GetString("QuestionPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ask for details when members register, e.g. "Staying for food?" or "Which drinks?"..
        /// </summary>
        public static string QuestionsHint {
            get {
                return ResourceManager.GetString("QuestionsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register ({0}).
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register by {0}.
        /// </summary>
        public static string RegisterUntil {
            get {
                return ResourceManager.GetString("RegisterUntil", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration is closed..
        /// </summary>
        public static string RegistrationClosed {
            get {
                return ResourceManager.GetString("RegistrationClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration closed on {0}..
        /// </summary>
        public static string RegistrationClosedAt {
            get {
                return ResourceManager.GetString("RegistrationClosedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} registrations.
        /// </summary>
        public static string RegistrationCount {
            get {
                return ResourceManager.GetString("RegistrationCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} registration.
        /// </summary>
        public static string RegistrationCountOne {
            get {
                return ResourceManager.GetString("RegistrationCountOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collect registrations, e.g. volunteers or who stays for food.
        /// </summary>
        public static string RegistrationEditorSubtitle {
            get {
                return ResourceManager.GetString("RegistrationEditorSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members can register.
        /// </summary>
        public static string RegistrationEnabledLabel {
            get {
                return ResourceManager.GetString("RegistrationEnabledLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You're registered – see you there! 🎉.
        /// </summary>
        public static string RegistrationSaved {
            get {
                return ResourceManager.GetString("RegistrationSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Let the organizers know you're coming.
        /// </summary>
        public static string RegistrationSubtitle {
            get {
                return ResourceManager.GetString("RegistrationSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration updated.
        /// </summary>
        public static string RegistrationUpdated {
            get {
                return ResourceManager.GetString("RegistrationUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration withdrawn.
        /// </summary>
        public static string RegistrationWithdrawn {
            get {
                return ResourceManager.GetString("RegistrationWithdrawn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} registrations have selected removed options. Their answers to these options will be deleted..
        /// </summary>
        public static string RemoveAnswersConfirm {
            get {
                return ResourceManager.GetString("RemoveAnswersConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove options?.
        /// </summary>
        public static string RemoveAnswersTitle {
            get {
                return ResourceManager.GetString("RemoveAnswersTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove registration.
        /// </summary>
        public static string RemoveRegistration {
            get {
                return ResourceManager.GetString("RemoveRegistration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove the registration of {0}?.
        /// </summary>
        public static string RemoveRegistrationConfirm {
            get {
                return ResourceManager.GetString("RemoveRegistrationConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Answer required.
        /// </summary>
        public static string RequiredLabel {
            get {
                return ResourceManager.GetString("RequiredLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveEvent {
            get {
                return ResourceManager.GetString("SaveEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is not possible in this browser..
        /// </summary>
        public static string ShareFailed {
            get {
                return ResourceManager.GetString("ShareFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign up in the app:.
        /// </summary>
        public static string ShareRegisterHint {
            get {
                return ResourceManager.GetString("ShareRegisterHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string ShowCalendar {
            get {
                return ResourceManager.GetString("ShowCalendar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show past events.
        /// </summary>
        public static string ShowPastEvents {
            get {
                return ResourceManager.GetString("ShowPastEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔘 Single choice.
        /// </summary>
        public static string SingleChoice {
            get {
                return ResourceManager.GetString("SingleChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First day.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        public static string TemplateMultipleChoice {
            get {
                return ResourceManager.GetString("TemplateMultipleChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choice with quantities (e.g. food).
        /// </summary>
        public static string TemplateQuantities {
            get {
                return ResourceManager.GetString("TemplateQuantities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single choice.
        /// </summary>
        public static string TemplateSingleChoice {
            get {
                return ResourceManager.GetString("TemplateSingleChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes / No question.
        /// </summary>
        public static string TemplateYesNo {
            get {
                return ResourceManager.GetString("TemplateYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Spring clean-up.
        /// </summary>
        public static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What the organizers need to plan for.
        /// </summary>
        public static string TotalsSubtitle {
            get {
                return ResourceManager.GetString("TotalsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E.g. drinks: any quantity (up to 99) regardless of the number of people..
        /// </summary>
        public static string UnlimitedQuantityHint {
            get {
                return ResourceManager.GetString("UnlimitedQuantityHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upcoming events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update registration.
        /// </summary>
        public static string UpdateRegistration {
            get {
                return ResourceManager.GetString("UpdateRegistration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string ViewList {
            get {
                return ResourceManager.GetString("ViewList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ViewMonth {
            get {
                return ResourceManager.GetString("ViewMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you really want to withdraw your registration?.
        /// </summary>
        public static string WithdrawConfirm {
            get {
                return ResourceManager.GetString("WithdrawConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Withdraw registration.
        /// </summary>
        public static string WithdrawTitle {
            get {
                return ResourceManager.GetString("WithdrawTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You're registered with {0} people..
        /// </summary>
        public static string YouAreRegistered {
            get {
                return ResourceManager.GetString("YouAreRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You're registered..
        /// </summary>
        public static string YouAreRegisteredOne {
            get {
                return ResourceManager.GetString("YouAreRegisteredOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You're in ({0}).
        /// </summary>
        public static string YoureIn {
            get {
                return ResourceManager.GetString("YoureIn", resourceCulture);
            }
        }
    }
}
