//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookennis.Client.Localization.Pages.ClubStatistics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClubStatisticsLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClubStatisticsLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookennis.Client.Localization.Pages.ClubStatistics.ClubStatisticsLocale", typeof(ClubStatisticsLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to played.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% of members played.
        /// </summary>
        public static string ActivationHint {
            get {
                return ResourceManager.GetString("ActivationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active players.
        /// </summary>
        public static string ActivePlayers {
            get {
                return ResourceManager.GetString("ActivePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11–20 bookings.
        /// </summary>
        public static string Activity_ElevenToTwenty {
            get {
                return ResourceManager.GetString("Activity_ElevenToTwenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 20.
        /// </summary>
        public static string Activity_MoreThanTwenty {
            get {
                return ResourceManager.GetString("Activity_MoreThanTwenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No booking.
        /// </summary>
        public static string Activity_None {
            get {
                return ResourceManager.GetString("Activity_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 booking.
        /// </summary>
        public static string Activity_One {
            get {
                return ResourceManager.GetString("Activity_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6–10 bookings.
        /// </summary>
        public static string Activity_SixToTen {
            get {
                return ResourceManager.GetString("Activity_SixToTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2–5 bookings.
        /// </summary>
        public static string Activity_TwoToFive {
            get {
                return ResourceManager.GetString("Activity_TwoToFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All bookings.
        /// </summary>
        public static string AllBookings {
            get {
                return ResourceManager.GetString("AllBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average age {0}.
        /// </summary>
        public static string AverageAge {
            get {
                return ResourceManager.GetString("AverageAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours per day.
        /// </summary>
        public static string AverageHoursPerDay {
            get {
                return ResourceManager.GetString("AverageHoursPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best season: {0}.
        /// </summary>
        public static string BestSeasonChip {
            get {
                return ResourceManager.GetString("BestSeasonChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best week ({0}).
        /// </summary>
        public static string BestWeek {
            get {
                return ResourceManager.GetString("BestWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking behavior.
        /// </summary>
        public static string BookingBehavior {
            get {
                return ResourceManager.GetString("BookingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When and how members book.
        /// </summary>
        public static string BookingBehaviorSubtitle {
            get {
                return ResourceManager.GetString("BookingBehaviorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings per member.
        /// </summary>
        public static string BookingsPerMember {
            get {
                return ResourceManager.GetString("BookingsPerMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busiest day.
        /// </summary>
        public static string BusiestDay {
            get {
                return ResourceManager.GetString("BusiestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occupied · {1} h booked.
        /// </summary>
        public static string CellDetail {
            get {
                return ResourceManager.GetString("CellDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club statistics.
        /// </summary>
        public static string ClubStatistics {
            get {
                return ResourceManager.GetString("ClubStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court occupancy.
        /// </summary>
        public static string CourtOccupancy {
            get {
                return ResourceManager.GetString("CourtOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Across all seasons, up to today.
        /// </summary>
        public static string CourtOccupancyAllTimeSubtitle {
            get {
                return ResourceManager.GetString("CourtOccupancyAllTimeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share of each hour the courts were booked – tap a cell for details.
        /// </summary>
        public static string CourtOccupancySubtitle {
            get {
                return ResourceManager.GetString("CourtOccupancySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current season is counted up to today..
        /// </summary>
        public static string CurrentSeasonNote {
            get {
                return ResourceManager.GetString("CurrentSeasonNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted until today ({0}).
        /// </summary>
        public static string DataUntil {
            get {
                return ResourceManager.GetString("DataUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0} of {1}.
        /// </summary>
        public static string DayOfSeason {
            get {
                return ResourceManager.GetString("DayOfSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day utilization.
        /// </summary>
        public static string DayQuality {
            get {
                return ResourceManager.GetString("DayQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much was played on each of the {0} days so far.
        /// </summary>
        public static string DayQualitySubtitle {
            get {
                return ResourceManager.GetString("DayQualitySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days with 3–5 h.
        /// </summary>
        public static string Days3To5 {
            get {
                return ResourceManager.GetString("Days3To5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days with 5–10 h.
        /// </summary>
        public static string Days5To10 {
            get {
                return ResourceManager.GetString("Days5To10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days without bookings.
        /// </summary>
        public static string DaysEmpty {
            get {
                return ResourceManager.GetString("DaysEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days left.
        /// </summary>
        public static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days with 10 h or more.
        /// </summary>
        public static string DaysOver10 {
            get {
                return ResourceManager.GetString("DaysOver10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days under 3 h.
        /// </summary>
        public static string DaysUnder3 {
            get {
                return ResourceManager.GetString("DaysUnder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age structure.
        /// </summary>
        public static string DemographicsOverSeasons {
            get {
                return ResourceManager.GetString("DemographicsOverSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age groups of the members per season.
        /// </summary>
        public static string DemographicsOverSeasonsSubtitle {
            get {
                return ResourceManager.GetString("DemographicsOverSeasonsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different players.
        /// </summary>
        public static string DistinctPlayers {
            get {
                return ResourceManager.GetString("DistinctPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        public static string EnrolledChip {
            get {
                return ResourceManager.GetString("EnrolledChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + {0} guests.
        /// </summary>
        public static string GuestsHint {
            get {
                return ResourceManager.GetString("GuestsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on {0} days.
        /// </summary>
        public static string HeatmapBasis {
            get {
                return ResourceManager.GetString("HeatmapBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular: {0} at {1} ({2}).
        /// </summary>
        public static string HottestSlot {
            get {
                return ResourceManager.GetString("HottestSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the {0} members without a booking.
        /// </summary>
        public static string InactiveMembersLink {
            get {
                return ResourceManager.GetString("InactiveMembersLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lapsed.
        /// </summary>
        public static string Lapsed {
            get {
                return ResourceManager.GetString("Lapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a red bar to open the lapsed members and copy their emails..
        /// </summary>
        public static string LapsedHint {
            get {
                return ResourceManager.GetString("LapsedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not re-enrolled from last season.
        /// </summary>
        public static string LapsedLink {
            get {
                return ResourceManager.GetString("LapsedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked in advance.
        /// </summary>
        public static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than a day.
        /// </summary>
        public static string LeadTime_LessThanADay {
            get {
                return ResourceManager.GetString("LeadTime_LessThanADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than a week.
        /// </summary>
        public static string LeadTime_MoreThanAWeek {
            get {
                return ResourceManager.GetString("LeadTime_MoreThanAWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1–2 days.
        /// </summary>
        public static string LeadTime_OneToTwoDays {
            get {
                return ResourceManager.GetString("LeadTime_OneToTwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3–7 days.
        /// </summary>
        public static string LeadTime_ThreeToSevenDays {
            get {
                return ResourceManager.GetString("LeadTime_ThreeToSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches.
        /// </summary>
        public static string MatchesCount {
            get {
                return ResourceManager.GetString("MatchesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches only.
        /// </summary>
        public static string MatchesOnly {
            get {
                return ResourceManager.GetString("MatchesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only play modes that count as match (booking limit, badges, leaderboard).
        /// </summary>
        public static string MatchesOnlyHint {
            get {
                return ResourceManager.GetString("MatchesOnlyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member activity.
        /// </summary>
        public static string MemberActivity {
            get {
                return ResourceManager.GetString("MemberActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who actually plays – and who does not.
        /// </summary>
        public static string MemberActivitySubtitle {
            get {
                return ResourceManager.GetString("MemberActivitySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string MemberDemographics {
            get {
                return ResourceManager.GetString("MemberDemographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age groups and gender of the enrolled members.
        /// </summary>
        public static string MemberDemographicsSubtitle {
            get {
                return ResourceManager.GetString("MemberDemographicsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members overall.
        /// </summary>
        public static string MembersEver {
            get {
                return ResourceManager.GetString("MembersEver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members overall.
        /// </summary>
        public static string MembersEverChip {
            get {
                return ResourceManager.GetString("MembersEverChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        public static string MembersTotal {
            get {
                return ResourceManager.GetString("MembersTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        public static string MetricActivationRate {
            get {
                return ResourceManager.GetString("MetricActivationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active players.
        /// </summary>
        public static string MetricActivePlayers {
            get {
                return ResourceManager.GetString("MetricActivePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string MetricBookings {
            get {
                return ResourceManager.GetString("MetricBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string MetricHours {
            get {
                return ResourceManager.GetString("MetricHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string MetricMembers {
            get {
                return ResourceManager.GetString("MetricMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        public static string MetricOccupancy {
            get {
                return ResourceManager.GetString("MetricOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most players in a week.
        /// </summary>
        public static string MostPlayersInAWeek {
            get {
                return ResourceManager.GetString("MostPlayersInAWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookings yet..
        /// </summary>
        public static string NoBookings {
            get {
                return ResourceManager.GetString("NoBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The season has not started yet..
        /// </summary>
        public static string NoDaysYet {
            get {
                return ResourceManager.GetString("NoDaysYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members enrolled..
        /// </summary>
        public static string NoMembers {
            get {
                return ResourceManager.GetString("NoMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has played yet..
        /// </summary>
        public static string NoPlayers {
            get {
                return ResourceManager.GetString("NoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seasons yet..
        /// </summary>
        public static string NoSeasons {
            get {
                return ResourceManager.GetString("NoSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        public static string Occupancy {
            get {
                return ResourceManager.GetString("Occupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0} members played at least once.
        /// </summary>
        public static string OfEnrolledPlayed {
            get {
                return ResourceManager.GetString("OfEnrolledPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overall.
        /// </summary>
        public static string OverallOccupancy {
            get {
                return ResourceManager.GetString("OverallOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours vs. {0} at this point.
        /// </summary>
        public static string PaceCaption {
            get {
                return ResourceManager.GetString("PaceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} h this season vs. {1} h.
        /// </summary>
        public static string PaceText {
            get {
                return ResourceManager.GetString("PaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours played.
        /// </summary>
        public static string PlayedHours {
            get {
                return ResourceManager.GetString("PlayedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players per booking.
        /// </summary>
        public static string PlayersPerBooking {
            get {
                return ResourceManager.GetString("PlayersPerBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play modes.
        /// </summary>
        public static string PlayModeUsage {
            get {
                return ResourceManager.GetString("PlayModeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours per play mode.
        /// </summary>
        public static string PlayModeUsageSubtitle {
            get {
                return ResourceManager.GetString("PlayModeUsageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prime time.
        /// </summary>
        public static string PrimeTime {
            get {
                return ResourceManager.GetString("PrimeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime time {0}.
        /// </summary>
        public static string PrimeTimeHint {
            get {
                return ResourceManager.GetString("PrimeTimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime time hours.
        /// </summary>
        public static string PrimeTimeLegend {
            get {
                return ResourceManager.GetString("PrimeTimeLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the hours in prime time.
        /// </summary>
        public static string PrimeTimeShare {
            get {
                return ResourceManager.GetString("PrimeTimeShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quietest: {0} at {1} ({2}).
        /// </summary>
        public static string QuietestSlot {
            get {
                return ResourceManager.GetString("QuietestSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from series.
        /// </summary>
        public static string RecurringHint {
            get {
                return ResourceManager.GetString("RecurringHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the bookings from series.
        /// </summary>
        public static string RecurringShare {
            get {
                return ResourceManager.GetString("RecurringShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member retention.
        /// </summary>
        public static string Retention {
            get {
                return ResourceManager.GetString("Retention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% stayed.
        /// </summary>
        public static string RetentionRate {
            get {
                return ResourceManager.GetString("RetentionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning, new and lapsed members per season.
        /// </summary>
        public static string RetentionSubtitle {
            get {
                return ResourceManager.GetString("RetentionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning.
        /// </summary>
        public static string Returning {
            get {
                return ResourceManager.GetString("Returning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string SeasonChip {
            get {
                return ResourceManager.GetString("SeasonChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season comparison.
        /// </summary>
        public static string SeasonComparison {
            get {
                return ResourceManager.GetString("SeasonComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a metric to compare the seasons.
        /// </summary>
        public static string SeasonComparisonSubtitle {
            get {
                return ResourceManager.GetString("SeasonComparisonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season progress.
        /// </summary>
        public static string SeasonProgress {
            get {
                return ResourceManager.GetString("SeasonProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seasons.
        /// </summary>
        public static string SeasonsChip {
            get {
                return ResourceManager.GetString("SeasonsChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string SeasonTitle {
            get {
                return ResourceManager.GetString("SeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniors.
        /// </summary>
        public static string Seniors {
            get {
                return ResourceManager.GetString("Seniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the {0} lapsed members.
        /// </summary>
        public static string ShowLapsedMembers {
            get {
                return ResourceManager.GetString("ShowLapsedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since {0}.
        /// </summary>
        public static string SinceSubtitle {
            get {
                return ResourceManager.GetString("SinceSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teenagers.
        /// </summary>
        public static string Teenagers {
            get {
                return ResourceManager.GetString("Teenagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most active players.
        /// </summary>
        public static string TopPlayers {
            get {
                return ResourceManager.GetString("TopPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most active players of all time.
        /// </summary>
        public static string TopPlayersAllTime {
            get {
                return ResourceManager.GetString("TopPlayersAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By hours on court.
        /// </summary>
        public static string TopPlayersSubtitle {
            get {
                return ResourceManager.GetString("TopPlayersSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours on court.
        /// </summary>
        public static string TotalHoursOnCourt {
            get {
                return ResourceManager.GetString("TotalHoursOnCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is {0} days of tennis non-stop.
        /// </summary>
        public static string TotalHoursText {
            get {
                return ResourceManager.GetString("TotalHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started yet.
        /// </summary>
        public static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} upcoming bookings.
        /// </summary>
        public static string UpcomingChip {
            get {
                return ResourceManager.GetString("UpcomingChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courts.
        /// </summary>
        public static string ViewCourts {
            get {
                return ResourceManager.GetString("ViewCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        public static string ViewWeekdays {
            get {
                return ResourceManager.GetString("ViewWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        public static string Weekdays {
            get {
                return ResourceManager.GetString("Weekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours played per weekday.
        /// </summary>
        public static string WeekdaysSubtitle {
            get {
                return ResourceManager.GetString("WeekdaysSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly trend.
        /// </summary>
        public static string WeeklyTrend {
            get {
                return ResourceManager.GetString("WeeklyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours played per week compared to the previous season.
        /// </summary>
        public static string WeeklyTrendSubtitle {
            get {
                return ResourceManager.GetString("WeeklyTrendSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks without bookings.
        /// </summary>
        public static string WeeksWithoutBookings {
            get {
                return ResourceManager.GetString("WeeksWithoutBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs..
        /// </summary>
        public static string YearsShort {
            get {
                return ResourceManager.GetString("YearsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% youth.
        /// </summary>
        public static string YouthShare {
            get {
                return ResourceManager.GetString("YouthShare", resourceCulture);
            }
        }
    }
}
