<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <WasmEnableSIMD>false</WasmEnableSIMD>
    <RunAOTCompilation>true</RunAOTCompilation>
    <WasmStripILAfterAOT>false</WasmStripILAfterAOT>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />

    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\Bookennis.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\BackendErrorCodeLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BackendErrorCodeLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Components\Booking\BookingSharedLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BookingSharedLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Components\Booking\PlayerSelectionLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PlayerSelectionLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Components\Family\FamilySharedLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FamilySharedLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Navigation\NavigationLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NavigationLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\Account\AccountLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AccountLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\Admin\AdminLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AdminLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\ClubShell\ClubShellLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClubShellLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\Calendar\CalendarLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CalendarLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\SubscriptionPlanner\SubscriptionPlannerLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SubscriptionPlannerLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\MyClub\MyClubLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MyClubLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\Trophies\TrophyLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TrophyLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\Statistics\StatisticsLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StatisticsLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Pages\Legal\LegalLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LegalLocale.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\SharedLocale.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedLocale.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Family\Family.razor.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\BackendErrorCodeLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BackendErrorCodeLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Components\Booking\BookingSharedLocale.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Components\Booking\BookingSharedLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BookingSharedLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Components\Booking\PlayerSelectionLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PlayerSelectionLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Components\Family\FamilySharedLocale.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Components\Family\FamilySharedLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>FamilySharedLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Navigation\NavigationLocale.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Navigation\NavigationLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NavigationLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Account\AccountLocale.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Account\AccountLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AccountLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Admin\AdminLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AdminLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Admin\AdminLocale.de.resx">
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\ClubShell\ClubShellLocale.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\ClubShell\ClubShellLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ClubShellLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Calendar\CalendarLocale.de.resx">
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Calendar\CalendarLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CalendarLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\SubscriptionPlanner\SubscriptionPlannerLocale.de.resx">
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\SubscriptionPlanner\SubscriptionPlannerLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SubscriptionPlannerLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\MyClub\MyClubLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MyClubLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Trophies\TrophyLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TrophyLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Statistics\StatisticsLocale.de.resx">
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Statistics\StatisticsLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>StatisticsLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Pages\Legal\LegalLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LegalLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\SharedLocale.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedLocale.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
