<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <Version>1.0.0</Version>
    <Authors>TenisAg</Authors>
    <Product>Bookennis</Product>

    <IsPackable>false</IsPackable>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <Features>strict</Features>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <!-- Disabled CA1707 to allow underscores in identifiers like test method names -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>
  </PropertyGroup>

</Project>