name: .Net build and tests

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: developer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./src/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore workload
        run: dotnet workload restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
